In [72]:
'''This program conducts stages 2-5 of the Henderson Sports' analytical model (data extraction, data preparation,
   data integration and data storage) (Adapted from: Holland and Shaw (2019).'''

"This program conducts stages 2-5 of the Henderson Sports' analytical model (data extraction, data preparation,\n   data integration and data storage) (Adapted from: Holland and Shaw (2019)."

"This program conducts stages 2-5 of the Henderson Sports' analytical model (data extraction, data preparation,\n   data integration and data storage) (Adapted from: Holland and Shaw (2019)."

In [143]:
# Import necessary libraries

import pandas as pd

# Title: User Guide - Pandas
# Author: N/A
# Date: No date
# Code Version: 2.2
# Source: "https://pandas.pydata.org/docs/user_guide/index.html"

In [74]:
# FBref
# Standard Stats

In [75]:
'''All of the following data is from the 2023-2024 football season.'''

'All of the following data is from the 2023-2024 football season.'

'All of the following data is from the 2023-2024 football season.'

In [144]:
# FBref link for Web Scraping and Data Extraction

# Firstly, a variable is created using the FBref website link 
url_df_FB = 'https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats'

# Next, the "pd.read_html()" function is used to extract the data from FBref's HTML table
# Table is extracted at "Index[0]"
df_FB = pd.read_html(url_df_FB)[0]
df_FB.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"


# Title: 2023-2024 Big 5 European Leagues: Standard Stats.
# Author: FBref
# Date: 2024
# Code Version: N/A
# Source: "https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats"

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Playing Time         ... Per 90 Minutes              \
                Born           MP Starts  ...            Ast   G+A  G-PK
0               2000           20     13  ...           0.07  0.07  0.00
1               2000           30     14  ...           0.14  0.28  0.14
2               2003            7      1  ...           0.89  0.89  0.00
3               2006            1      0  ...           0.00  0.00  0.00
4               1987           31     31  ...           0.00  0.13  0.10

                                           Unnamed: 37_level_0
  G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG             Matches
0   0.07  0.00  0.06   0.06  0.00     0.06             Matches
1   0.28  0.14  0.13   0.27  0.14     0.27             Matches
2   0.89  0.11  0.07   0.19  0.11     0.19             Matches
3   0.00  0.00  0.00   0.00  0.00     0.00             Matches
4   0.10  0.11  0.01   0.12  0.09     0.09             Matches

[5 rows x 38 columns]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Playing Time         ... Per 90 Minutes              \
                Born           MP Starts  ...            Ast   G+A  G-PK
0               2000           20     13  ...           0.07  0.07  0.00
1               2000           30     14  ...           0.14  0.28  0.14
2               2003            7      1  ...           0.89  0.89  0.00
3               2006            1      0  ...           0.00  0.00  0.00
4               1987           31     31  ...           0.00  0.13  0.10

                                           Unnamed: 37_level_0
  G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG             Matches
0   0.07  0.00  0.06   0.06  0.00     0.06             Matches
1   0.28  0.14  0.13   0.27  0.14     0.27             Matches
2   0.89  0.11  0.07   0.19  0.11     0.19             Matches
3   0.00  0.00  0.00   0.00  0.00     0.00             Matches
4   0.10  0.11  0.01   0.12  0.09     0.09             Matches

[5 rows x 38 columns]

In [145]:
# Now to get rid of the "multi indexing"
df_FB.columns = [' '.join(col).strip() for col in df_FB.columns]

df_FB = df_FB.reset_index(drop=True)
df_FB.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Playing Time MP,Playing Time Starts,...,Per 90 Minutes Ast,Per 90 Minutes G+A,Per 90 Minutes G-PK,Per 90 Minutes G+A-PK,Per 90 Minutes xG,Per 90 Minutes xAG,Per 90 Minutes xG+xAG,Per 90 Minutes npxG,Per 90 Minutes npxG+xAG,Unnamed: 37_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,20,13,...,0.07,0.07,0.00,0.07,0.00,0.06,0.06,0.00,0.06,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,30,14,...,0.14,0.28,0.14,0.28,0.14,0.13,0.27,0.14,0.27,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,7,1,...,0.89,0.89,0.00,0.89,0.11,0.07,0.19,0.11,0.19,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,1,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,31,31,...,0.00,0.13,0.10,0.10,0.11,0.01,0.12,0.09,0.09,Matches

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Playing Time MP,Playing Time Starts,...,Per 90 Minutes Ast,Per 90 Minutes G+A,Per 90 Minutes G-PK,Per 90 Minutes G+A-PK,Per 90 Minutes xG,Per 90 Minutes xAG,Per 90 Minutes xG+xAG,Per 90 Minutes npxG,Per 90 Minutes npxG+xAG,Unnamed: 37_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,20,13,...,0.07,0.07,0.00,0.07,0.00,0.06,0.06,0.00,0.06,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,30,14,...,0.14,0.28,0.14,0.28,0.14,0.13,0.27,0.14,0.27,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,7,1,...,0.89,0.89,0.00,0.89,0.11,0.07,0.19,0.11,0.19,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,1,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,31,31,...,0.00,0.13,0.10,0.10,0.11,0.01,0.12,0.09,0.09,Matches

In [78]:
# Now, this code creates a list with the new column names
# Removes unwanted parts of the column name such as "0_level_0"
new_col_FB = []
for new_FB in df_FB.columns:
    if 'level_0' in new_FB:
        new_col_name_FB = new_FB.split()[-1]
        new_col_FB.append(new_col_name_FB)  
    else:
        new_col_FB.append(new_FB)  

# This part renames the columns
df_FB.columns = new_col_FB
df_FB = df_FB.fillna(0)

df_FB.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Author: Open AI
# Date: 2024
# Source: ChatGPT [online] "https://chat.openai.com/"

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,...,Per 90 Minutes Ast,Per 90 Minutes G+A,Per 90 Minutes G-PK,Per 90 Minutes G+A-PK,Per 90 Minutes xG,Per 90 Minutes xAG,Per 90 Minutes xG+xAG,Per 90 Minutes npxG,Per 90 Minutes npxG+xAG,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,20,13,...,0.07,0.07,0.00,0.07,0.00,0.06,0.06,0.00,0.06,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,30,14,...,0.14,0.28,0.14,0.28,0.14,0.13,0.27,0.14,0.27,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,7,1,...,0.89,0.89,0.00,0.89,0.11,0.07,0.19,0.11,0.19,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,1,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,31,31,...,0.00,0.13,0.10,0.10,0.11,0.01,0.12,0.09,0.09,Matches

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,...,Per 90 Minutes Ast,Per 90 Minutes G+A,Per 90 Minutes G-PK,Per 90 Minutes G+A-PK,Per 90 Minutes xG,Per 90 Minutes xAG,Per 90 Minutes xG+xAG,Per 90 Minutes npxG,Per 90 Minutes npxG+xAG,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,20,13,...,0.07,0.07,0.00,0.07,0.00,0.06,0.06,0.00,0.06,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,30,14,...,0.14,0.28,0.14,0.28,0.14,0.13,0.27,0.14,0.27,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,7,1,...,0.89,0.89,0.00,0.89,0.11,0.07,0.19,0.11,0.19,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,1,0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,31,31,...,0.00,0.13,0.10,0.10,0.11,0.01,0.12,0.09,0.09,Matches

In [79]:
# Defensive Stats

In [80]:
# FBref link for defensive actions
# Repeat process done for standard stats
url_df_FB_DEF = 'https://fbref.com/en/comps/Big5/2023-2024/defense/players/2023-2024-Big-5-European-Leagues-Stats'

df_FB_DEF = pd.read_html(url_df_FB_DEF)[0]
df_FB_DEF.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Title: 2023-2024 Big 5 European Leagues: Defensive Actions.
# Author: FBref
# Date: 2024
# Code Version: N/A
# Source: "https://fbref.com/en/comps/Big5/2023-2024/defense/players/2023-2024-Big-5-European-Leagues-Stats"

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 Tackles  ... Challenges      Blocks  \
                Born                90s     Tkl  ...       Tkl% Lost Blocks
0               2000               13.7      29  ...       58.8   14      9
1               2000               14.1      32  ...       50.0   16     26
2               2003                1.1       2  ...      100.0    0      2
3               2006                0.0       0  ...        NaN    0      0
4               1987               30.9      64  ...       57.8   19     51

           Unnamed: 21_level_0 Unnamed: 22_level_0 Unnamed: 23_level_0  \
   Sh Pass                 Int             Tkl+Int                 Clr
0   5    4                   8                  37                  27
1   1   25                   2                  34                   4
2   0    2                   0                   2                   0
3   0    0                   0                   0                   0
4  32   19                  39                 103                 109

  Unnamed: 24_level_0 Unnamed: 25_level_0
                  Err             Matches
0                   0             Matches
1                   0             Matches
2                   0             Matches
3                   0             Matches
4                   2             Matches

[5 rows x 26 columns]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 Tackles  ... Challenges      Blocks  \
                Born                90s     Tkl  ...       Tkl% Lost Blocks
0               2000               13.7      29  ...       58.8   14      9
1               2000               14.1      32  ...       50.0   16     26
2               2003                1.1       2  ...      100.0    0      2
3               2006                0.0       0  ...        NaN    0      0
4               1987               30.9      64  ...       57.8   19     51

           Unnamed: 21_level_0 Unnamed: 22_level_0 Unnamed: 23_level_0  \
   Sh Pass                 Int             Tkl+Int                 Clr
0   5    4                   8                  37                  27
1   1   25                   2                  34                   4
2   0    2                   0                   2                   0
3   0    0                   0                   0                   0
4  32   19                  39                 103                 109

  Unnamed: 24_level_0 Unnamed: 25_level_0
                  Err             Matches
0                   0             Matches
1                   0             Matches
2                   0             Matches
3                   0             Matches
4                   2             Matches

[5 rows x 26 columns]

In [81]:
# Repeat process done for standard stats

df_FB_DEF.columns = [' '.join(col1).strip() for col1 in df_FB_DEF.columns]

df_FB_DEF = df_FB_DEF.reset_index(drop=True)
df_FB_DEF.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Tackles Tkl,...,Challenges Tkl%,Challenges Lost,Blocks Blocks,Blocks Sh,Blocks Pass,Unnamed: 21_level_0 Int,Unnamed: 22_level_0 Tkl+Int,Unnamed: 23_level_0 Clr,Unnamed: 24_level_0 Err,Unnamed: 25_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,29,...,58.8,14,9,5,4,8,37,27,0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,32,...,50.0,16,26,1,25,2,34,4,0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,2,...,100.0,0,2,0,2,0,2,0,0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,NaN,0,0,0,0,0,0,0,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,64,...,57.8,19,51,32,19,39,103,109,2,Matches

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Tackles Tkl,...,Challenges Tkl%,Challenges Lost,Blocks Blocks,Blocks Sh,Blocks Pass,Unnamed: 21_level_0 Int,Unnamed: 22_level_0 Tkl+Int,Unnamed: 23_level_0 Clr,Unnamed: 24_level_0 Err,Unnamed: 25_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,29,...,58.8,14,9,5,4,8,37,27,0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,32,...,50.0,16,26,1,25,2,34,4,0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,2,...,100.0,0,2,0,2,0,2,0,0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,NaN,0,0,0,0,0,0,0,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,64,...,57.8,19,51,32,19,39,103,109,2,Matches

In [82]:
# Repeat process done for standard stats
new_col_DEF = []
for new_DEF in df_FB_DEF.columns:
    if 'level_0' in new_DEF:
        new_col_name_DEF = new_DEF.split()[-1]
        new_col_DEF.append(new_col_name_DEF)  
    else:
        new_col_DEF.append(new_DEF)  

df_FB_DEF.columns = new_col_DEF
df_FB_DEF_1 = df_FB_DEF.fillna(0)

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Author: Open AI
# Date: 2024
# Source: ChatGPT [online] "https://chat.openai.com/"

In [83]:
# Dropping unncecessary columns that are not needed for data analysis 
df_FB_DEF_1 = df_FB_DEF_1.drop(columns=['Matches', 'Comp', 'Born', 'Pos', 'Nation', 'Squad', 'Comp', 'Age', '90s'])


df_FB_DEF_1

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Rk,Player,Tackles Tkl,Tackles TklW,Tackles Def 3rd,Tackles Mid 3rd,Tackles Att 3rd,Challenges Tkl,Challenges Att,Challenges Tkl%,Challenges Lost,Blocks Blocks,Blocks Sh,Blocks Pass,Int,Tkl+Int,Clr,Err
0,1,Max Aarons,29,19,20,7,2,20,34,58.8,14,9,5,4,8,37,27,0
1,2,Brenden Aaronson,32,18,13,13,6,16,32,50.0,16,26,1,25,2,34,4,0
2,3,Paxten Aaronson,2,2,1,1,0,1,1,100.0,0,2,0,2,0,2,0,0
3,4,Keyliane Abdallah,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,Yunis Abdelhamid,64,35,36,23,5,26,45,57.8,19,51,32,19,39,103,109,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2849,Martin Ødegaard,49,17,18,21,10,17,58,29.3,41,23,1,22,15,64,5,0
2962,2850,Milan Đurić,1,0,0,0,1,0,3,0.0,3,0,0,0,1,2,13,0
2963,Rk,Player,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Tkl,Att,Tkl%,Lost,Blocks,Sh,Pass,Int,Tkl+Int,Clr,Err
2964,2851,Milan Đurić,5,5,0,5,0,2,4,50.0,2,6,2,4,0,5,27,0
2965,2852,Mateusz Łęgowski,23,12,8,12,3,11,26,42.3,15,13,2,11,7,30,16,0

,Rk,Player,Tackles Tkl,Tackles TklW,Tackles Def 3rd,Tackles Mid 3rd,Tackles Att 3rd,Challenges Tkl,Challenges Att,Challenges Tkl%,Challenges Lost,Blocks Blocks,Blocks Sh,Blocks Pass,Int,Tkl+Int,Clr,Err
0,1,Max Aarons,29,19,20,7,2,20,34,58.8,14,9,5,4,8,37,27,0
1,2,Brenden Aaronson,32,18,13,13,6,16,32,50.0,16,26,1,25,2,34,4,0
2,3,Paxten Aaronson,2,2,1,1,0,1,1,100.0,0,2,0,2,0,2,0,0
3,4,Keyliane Abdallah,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,Yunis Abdelhamid,64,35,36,23,5,26,45,57.8,19,51,32,19,39,103,109,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2849,Martin Ødegaard,49,17,18,21,10,17,58,29.3,41,23,1,22,15,64,5,0
2962,2850,Milan Đurić,1,0,0,0,1,0,3,0.0,3,0,0,0,1,2,13,0
2963,Rk,Player,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Tkl,Att,Tkl%,Lost,Blocks,Sh,Pass,Int,Tkl+Int,Clr,Err
2964,2851,Milan Đurić,5,5,0,5,0,2,4,50.0,2,6,2,4,0,5,27,0
2965,2852,Mateusz Łęgowski,23,12,8,12,3,11,26,42.3,15,13,2,11,7,30,16,0

In [84]:
# Possession Stats

In [85]:
# FBref link for Possession
# Repeat process again for possession stats 
url_df_FB_POSS = 'https://fbref.com/en/comps/Big5/2023-2024/possession/players/2023-2024-Big-5-European-Leagues-Stats'

df_FB_POSS = pd.read_html(url_df_FB_POSS)[0]
df_FB_POSS.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Title: 2023-2024 Big 5 European Leagues: Possession.
# Author: FBref
# Date: 2024
# Code Version: N/A
# Source: "https://fbref.com/en/comps/Big5/2023-2024/possession/players/2023-2024-Big-5-European-Leagues-Stats"

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 Touches  ... Carries                   \
                Born                90s Touches  ... TotDist PrgDist PrgC 1/3
0               2000               13.7     711  ...    2174    1121   22  12
1               2000               14.1     675  ...    2721    1387   37  29
2               2003                1.1      72  ...     193      50    2   0
3               2006                0.0       1  ...       3       0    0   0
4               1987               30.9    2185  ...    8663    4921   36  19

              Receiving      Unnamed: 31_level_0
  CPA Mis Dis       Rec PrgR             Matches
0   7  13   8       371   26             Matches
1   9  41  38       457   91             Matches
2   1   5   4        46    7             Matches
3   0   0   0         1    0             Matches
4   0  23   4      1403    9             Matches

[5 rows x 32 columns]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 Touches  ... Carries                   \
                Born                90s Touches  ... TotDist PrgDist PrgC 1/3
0               2000               13.7     711  ...    2174    1121   22  12
1               2000               14.1     675  ...    2721    1387   37  29
2               2003                1.1      72  ...     193      50    2   0
3               2006                0.0       1  ...       3       0    0   0
4               1987               30.9    2185  ...    8663    4921   36  19

              Receiving      Unnamed: 31_level_0
  CPA Mis Dis       Rec PrgR             Matches
0   7  13   8       371   26             Matches
1   9  41  38       457   91             Matches
2   1   5   4        46    7             Matches
3   0   0   0         1    0             Matches
4   0  23   4      1403    9             Matches

[5 rows x 32 columns]

In [86]:
# creating a dataset with the same headers but without multi indexing
df_FB_POSS.columns = [' '.join(col_poss).strip() for col_poss in df_FB_POSS.columns]

df_FB_POSS = df_FB_POSS.reset_index(drop=True)
df_FB_POSS.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Touches Touches,...,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR,Unnamed: 31_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,711,...,2174,1121,22,12,7,13,8,371,26,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,675,...,2721,1387,37,29,9,41,38,457,91,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,72,...,193,50,2,0,1,5,4,46,7,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,1,...,3,0,0,0,0,0,0,1,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,2185,...,8663,4921,36,19,0,23,4,1403,9,Matches

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Touches Touches,...,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR,Unnamed: 31_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,711,...,2174,1121,22,12,7,13,8,371,26,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,675,...,2721,1387,37,29,9,41,38,457,91,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,72,...,193,50,2,0,1,5,4,46,7,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,1,...,3,0,0,0,0,0,0,1,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,2185,...,8663,4921,36,19,0,23,4,1403,9,Matches

In [87]:
new_col_POSS = []
for new_POSS in df_FB_POSS.columns:
    if 'level_0' in new_POSS:
        new_col_name_POSS = new_POSS.split()[-1]
        new_col_POSS.append(new_col_name_POSS)  
    else:
        new_col_POSS.append(new_POSS)  

df_FB_POSS.columns = new_col_POSS
df_FB_POSS = df_FB_POSS.fillna(0)

df_FB_POSS.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Author: Open AI
# Date: 2024
# Source: ChatGPT [online] "https://chat.openai.com/"

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Touches Touches,...,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,711,...,2174,1121,22,12,7,13,8,371,26,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,675,...,2721,1387,37,29,9,41,38,457,91,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,72,...,193,50,2,0,1,5,4,46,7,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,1,...,3,0,0,0,0,0,0,1,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,2185,...,8663,4921,36,19,0,23,4,1403,9,Matches

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Touches Touches,...,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,711,...,2174,1121,22,12,7,13,8,371,26,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,675,...,2721,1387,37,29,9,41,38,457,91,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,72,...,193,50,2,0,1,5,4,46,7,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,1,...,3,0,0,0,0,0,0,1,0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,2185,...,8663,4921,36,19,0,23,4,1403,9,Matches

In [88]:
# Dropping unecessary columns that are no longer needed 
df_FB_POSS = df_FB_POSS.drop(columns=['Matches', 'Comp', 'Born', 'Pos', 'Nation', 'Squad', 'Comp', 'Age', '90s'])

df_FB_POSS

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Rk,Player,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,Touches Att 3rd,Touches Att Pen,Touches Live,Take-Ons Att,...,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR
0,1,Max Aarons,711,43,252,303,165,11,711,34,...,364,2174,1121,22,12,7,13,8,371,26
1,2,Brenden Aaronson,675,11,108,301,293,47,675,77,...,406,2721,1387,37,29,9,41,38,457,91
2,3,Paxten Aaronson,72,0,6,39,28,5,72,7,...,43,193,50,2,0,1,5,4,46,7
3,4,Keyliane Abdallah,1,0,0,1,0,0,1,0,...,1,3,0,0,0,0,0,0,1,0
4,5,Yunis Abdelhamid,2185,293,976,1119,114,35,2184,15,...,1506,8663,4921,36,19,0,23,4,1403,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2849,Martin Ødegaard,2326,24,244,926,1173,165,2324,81,...,1563,8190,3514,91,83,37,53,58,1827,202
2962,2850,Milan Đurić,421,14,41,227,153,46,418,3,...,183,529,151,3,6,1,22,8,352,33
2963,Rk,Player,Touches,Def Pen,Def 3rd,Mid 3rd,Att 3rd,Att Pen,Live,Att,...,Carries,TotDist,PrgDist,PrgC,1/3,CPA,Mis,Dis,Rec,PrgR
2964,2851,Milan Đurić,381,32,51,227,104,37,381,4,...,157,458,108,2,2,1,24,14,323,31
2965,2852,Mateusz Łęgowski,504,31,120,283,111,11,504,21,...,265,1526,757,16,13,3,20,12,294,17

,Rk,Player,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,Touches Att 3rd,Touches Att Pen,Touches Live,Take-Ons Att,...,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR
0,1,Max Aarons,711,43,252,303,165,11,711,34,...,364,2174,1121,22,12,7,13,8,371,26
1,2,Brenden Aaronson,675,11,108,301,293,47,675,77,...,406,2721,1387,37,29,9,41,38,457,91
2,3,Paxten Aaronson,72,0,6,39,28,5,72,7,...,43,193,50,2,0,1,5,4,46,7
3,4,Keyliane Abdallah,1,0,0,1,0,0,1,0,...,1,3,0,0,0,0,0,0,1,0
4,5,Yunis Abdelhamid,2185,293,976,1119,114,35,2184,15,...,1506,8663,4921,36,19,0,23,4,1403,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2849,Martin Ødegaard,2326,24,244,926,1173,165,2324,81,...,1563,8190,3514,91,83,37,53,58,1827,202
2962,2850,Milan Đurić,421,14,41,227,153,46,418,3,...,183,529,151,3,6,1,22,8,352,33
2963,Rk,Player,Touches,Def Pen,Def 3rd,Mid 3rd,Att 3rd,Att Pen,Live,Att,...,Carries,TotDist,PrgDist,PrgC,1/3,CPA,Mis,Dis,Rec,PrgR
2964,2851,Milan Đurić,381,32,51,227,104,37,381,4,...,157,458,108,2,2,1,24,14,323,31
2965,2852,Mateusz Łęgowski,504,31,120,283,111,11,504,21,...,265,1526,757,16,13,3,20,12,294,17

In [89]:
# Other important stats

In [90]:
# FBref link for 'Miscellaneous Stats'
# Repeat process again for miscellaneous stats 
url_df_FB_other = 'https://fbref.com/en/comps/Big5/2023-2024/misc/players/2023-2024-Big-5-European-Leagues-Stats'

df_FB_Other = pd.read_html(url_df_FB_other)[0]
df_FB_Other.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Title: 2023-2024 Big 5 European Leagues: Miscellaneous Stats.
# Author: FBref
# Date: 2024
# Code Version: N/A
# Source: "https://fbref.com/en/comps/Big5/2023-2024/misc/players/2023-2024-Big-5-European-Leagues-Stats"

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 Performance  ...                       \
                Born                90s        CrdY  ... Int TklW PKwon PKcon
0               2000               13.7           1  ...   8   19     0     1
1               2000               14.1           3  ...   2   18     0     0
2               2003                1.1           0  ...   0    2     0     0
3               2006                0.0           0  ...   0    0     0     0
4               1987               30.9           5  ...  39   35     0     0

           Aerial Duels             Unnamed: 25_level_0
  OG Recov          Won Lost   Won%             Matches
0  0    75            5   11   31.3             Matches
1  0    88           13   16   44.8             Matches
2  0     5            3    0  100.0             Matches
3  0     0            0    1    0.0             Matches
4  1   149           61   37   62.2             Matches

[5 rows x 26 columns]

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player             Nation                Pos
0                  1         Max Aarons            eng ENG                 DF
1                  2   Brenden Aaronson             us USA              MF,FW
2                  3    Paxten Aaronson             us USA                 MF
3                  4  Keyliane Abdallah             fr FRA                 FW
4                  5   Yunis Abdelhamid             ma MAR                 DF

  Unnamed: 4_level_0  Unnamed: 5_level_0 Unnamed: 6_level_0  \
               Squad                Comp                Age
0        Bournemouth  eng Premier League                 23
1       Union Berlin       de Bundesliga                 22
2     Eint Frankfurt       de Bundesliga                 19
3          Marseille          fr Ligue 1                 17
4              Reims          fr Ligue 1                 35

  Unnamed: 7_level_0 Unnamed: 8_level_0 Performance  ...                       \
                Born                90s        CrdY  ... Int TklW PKwon PKcon
0               2000               13.7           1  ...   8   19     0     1
1               2000               14.1           3  ...   2   18     0     0
2               2003                1.1           0  ...   0    2     0     0
3               2006                0.0           0  ...   0    0     0     0
4               1987               30.9           5  ...  39   35     0     0

           Aerial Duels             Unnamed: 25_level_0
  OG Recov          Won Lost   Won%             Matches
0  0    75            5   11   31.3             Matches
1  0    88           13   16   44.8             Matches
2  0     5            3    0  100.0             Matches
3  0     0            0    1    0.0             Matches
4  1   149           61   37   62.2             Matches

[5 rows x 26 columns]

In [91]:
# creating a dataset with the same headers but without multi indexing
df_FB_Other.columns = [' '.join(col_other).strip() for col_other in df_FB_Other.columns]

df_FB_Other = df_FB_Other.reset_index(drop=True)
df_FB_Other.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Performance CrdY,...,Performance Int,Performance TklW,Performance PKwon,Performance PKcon,Performance OG,Performance Recov,Aerial Duels Won,Aerial Duels Lost,Aerial Duels Won%,Unnamed: 25_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,1,...,8,19,0,1,0,75,5,11,31.3,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,3,...,2,18,0,0,0,88,13,16,44.8,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,0,...,0,2,0,0,0,5,3,0,100.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,0,0,0,0,0,0,0,1,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,5,...,39,35,0,0,1,149,61,37,62.2,Matches

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Performance CrdY,...,Performance Int,Performance TklW,Performance PKwon,Performance PKcon,Performance OG,Performance Recov,Aerial Duels Won,Aerial Duels Lost,Aerial Duels Won%,Unnamed: 25_level_0 Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,1,...,8,19,0,1,0,75,5,11,31.3,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,3,...,2,18,0,0,0,88,13,16,44.8,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,0,...,0,2,0,0,0,5,3,0,100.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,0,0,0,0,0,0,0,1,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,5,...,39,35,0,0,1,149,61,37,62.2,Matches

In [92]:
# Repeat the process

new_col_Other = []
for new_Other in df_FB_Other.columns:
    if 'level_0' in new_Other:
        new_col_name_Other = new_Other.split()[-1]
        new_col_Other.append(new_col_name_Other)  
    else:
        new_col_Other.append(new_Other)  

df_FB_Other.columns = new_col_Other
df_FB_Other = df_FB_Other.fillna(0)

df_FB_Other.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Author: Open AI
# Date: 2024
# Source: ChatGPT [online] "https://chat.openai.com/"

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Performance CrdY,...,Performance Int,Performance TklW,Performance PKwon,Performance PKcon,Performance OG,Performance Recov,Aerial Duels Won,Aerial Duels Lost,Aerial Duels Won%,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,1,...,8,19,0,1,0,75,5,11,31.3,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,3,...,2,18,0,0,0,88,13,16,44.8,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,0,...,0,2,0,0,0,5,3,0,100.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,0,0,0,0,0,0,0,1,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,5,...,39,35,0,0,1,149,61,37,62.2,Matches

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Performance CrdY,...,Performance Int,Performance TklW,Performance PKwon,Performance PKcon,Performance OG,Performance Recov,Aerial Duels Won,Aerial Duels Lost,Aerial Duels Won%,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,1,...,8,19,0,1,0,75,5,11,31.3,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,3,...,2,18,0,0,0,88,13,16,44.8,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,0,...,0,2,0,0,0,5,3,0,100.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,...,0,0,0,0,0,0,0,1,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,5,...,39,35,0,0,1,149,61,37,62.2,Matches

In [93]:
# Dropping unecessary columns that are no longer needed 
df_FB_Other = df_FB_Other.drop(columns=['Matches', 'Comp', 'Born', 'Pos', 'Nation', 'Squad', 'Comp', 'Age', '90s',
                                       'Rk', 'Performance CrdY', 'Performance CrdR', 'Performance 2CrdY',
                                       'Performance Int', 'Performance TklW', ])

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

In [94]:
# FBref Goalkeeper link
# Rpeat process for Goalkeeper stats
url_GK_FB_1 = 'https://fbref.com/en/comps/Big5/2023-2024/keepers/players/2023-2024-Big-5-European-Leagues-Stats'

GK_FB_1 = pd.read_html(url_GK_FB_1)[0]
GK_FB_1.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Title: 2023-2024 Big 5 European Leagues: Goalkeeping.
# Author: FBref
# Date: 2024
# Code Version: N/A
# Source: "https://fbref.com/en/comps/Big5/2023-2024/keepers/players/2023-2024-Big-5-European-Leagues-Stats"

  Unnamed: 0_level_0  Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk              Player             Nation
0                  1  Julen Agirrezabala             es ESP
1                  2             Alisson             br BRA
2                  3     Alphonse Areola             fr FRA
3                  4       Simone Aresti             it ITA
4                  5   Kepa Arrizabalaga             es ESP

  Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                 Pos              Squad                Comp
0                 GK      Athletic Club          es La Liga
1                 GK          Liverpool  eng Premier League
2                 GK           West Ham  eng Premier League
3                 GK           Cagliari          it Serie A
4                 GK        Real Madrid          es La Liga

  Unnamed: 6_level_0 Unnamed: 7_level_0 Playing Time         ... Performance  \
                 Age               Born           MP Starts  ...           D
0                 22               2000            4      2  ...           0
1                 30               1992           28     28  ...           8
2                 30               1993           31     31  ...           9
3                 37               1986            1      0  ...           0
4                 28               1994           14     13  ...           2

                Penalty Kicks                    Unnamed: 27_level_0
    L CS    CS%         PKatt PKA PKsv PKm Save%             Matches
0   1  2  100.0             0   0    0   0   NaN             Matches
1   4  8   28.6             1   1    0   0   0.0             Matches
2  11  4   12.9             7   5    2   0  28.6             Matches
3   0  0    NaN             1   1    0   0   0.0             Matches
4   1  8   61.5             0   0    0   0   NaN             Matches

[5 rows x 28 columns]

  Unnamed: 0_level_0  Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk              Player             Nation
0                  1  Julen Agirrezabala             es ESP
1                  2             Alisson             br BRA
2                  3     Alphonse Areola             fr FRA
3                  4       Simone Aresti             it ITA
4                  5   Kepa Arrizabalaga             es ESP

  Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                 Pos              Squad                Comp
0                 GK      Athletic Club          es La Liga
1                 GK          Liverpool  eng Premier League
2                 GK           West Ham  eng Premier League
3                 GK           Cagliari          it Serie A
4                 GK        Real Madrid          es La Liga

  Unnamed: 6_level_0 Unnamed: 7_level_0 Playing Time         ... Performance  \
                 Age               Born           MP Starts  ...           D
0                 22               2000            4      2  ...           0
1                 30               1992           28     28  ...           8
2                 30               1993           31     31  ...           9
3                 37               1986            1      0  ...           0
4                 28               1994           14     13  ...           2

                Penalty Kicks                    Unnamed: 27_level_0
    L CS    CS%         PKatt PKA PKsv PKm Save%             Matches
0   1  2  100.0             0   0    0   0   NaN             Matches
1   4  8   28.6             1   1    0   0   0.0             Matches
2  11  4   12.9             7   5    2   0  28.6             Matches
3   0  0    NaN             1   1    0   0   0.0             Matches
4   1  8   61.5             0   0    0   0   NaN             Matches

[5 rows x 28 columns]

In [95]:
GK_FB_1.columns = [' '.join(col).strip() for col in GK_FB_1.columns]

GK_FB_1 = GK_FB_1.reset_index(drop=True)
GK_FB_1.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Playing Time MP,Playing Time Starts,...,Performance D,Performance L,Performance CS,Performance CS%,Penalty Kicks PKatt,Penalty Kicks PKA,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Unnamed: 27_level_0 Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,4,2,...,0,1,2,100.0,0,0,0,0,NaN,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28,28,...,8,4,8,28.6,1,1,0,0,0.0,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,31,31,...,9,11,4,12.9,7,5,2,0,28.6,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,1,0,...,0,0,0,NaN,1,1,0,0,0.0,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,14,13,...,2,1,8,61.5,0,0,0,0,NaN,Matches

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Playing Time MP,Playing Time Starts,...,Performance D,Performance L,Performance CS,Performance CS%,Penalty Kicks PKatt,Penalty Kicks PKA,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Unnamed: 27_level_0 Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,4,2,...,0,1,2,100.0,0,0,0,0,NaN,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28,28,...,8,4,8,28.6,1,1,0,0,0.0,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,31,31,...,9,11,4,12.9,7,5,2,0,28.6,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,1,0,...,0,0,0,NaN,1,1,0,0,0.0,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,14,13,...,2,1,8,61.5,0,0,0,0,NaN,Matches

In [96]:
# Repeat the process

new_col_GK_1 = []
for new_GK_1 in GK_FB_1.columns:
    if 'level_0' in new_GK_1:
        new_col_name_GK_1 = new_GK_1.split()[-1]
        new_col_GK_1.append(new_col_name_GK_1)   
    else:
        new_col_GK_1.append(new_GK_1)  

GK_FB_1.columns = new_col_GK_1
GK_FB_1 = GK_FB_1.fillna(0)

GK_FB_1.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Author: Open AI
# Date: 2024
# Source: ChatGPT [online] "https://chat.openai.com/"

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,...,Performance D,Performance L,Performance CS,Performance CS%,Penalty Kicks PKatt,Penalty Kicks PKA,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,4,2,...,0,1,2,100.0,0,0,0,0,0,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28,28,...,8,4,8,28.6,1,1,0,0,0.0,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,31,31,...,9,11,4,12.9,7,5,2,0,28.6,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,1,0,...,0,0,0,0,1,1,0,0,0.0,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,14,13,...,2,1,8,61.5,0,0,0,0,0,Matches

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,...,Performance D,Performance L,Performance CS,Performance CS%,Penalty Kicks PKatt,Penalty Kicks PKA,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,4,2,...,0,1,2,100.0,0,0,0,0,0,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28,28,...,8,4,8,28.6,1,1,0,0,0.0,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,31,31,...,9,11,4,12.9,7,5,2,0,28.6,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,1,0,...,0,0,0,0,1,1,0,0,0.0,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,14,13,...,2,1,8,61.5,0,0,0,0,0,Matches

In [97]:
# Dropping columns that are not needed for the rest of the project
Basic_GK_df = GK_FB_1.drop(columns=['Performance GA', 'Rk', 'Performance GA90', 'Born', 'Performance SoTA', 
                                    'Performance Saves', 'Performance W', 'Performance D',
                                    'Performance L', 'Performance CS', 'Performance CS%', 'Penalty Kicks PKatt', 
                                    'Penalty Kicks PKA', 'Matches', '90s', 'Playing Time MP', 'Age', 'Nation', 'Pos',
                                    'Playing Time Starts', 'Playing Time Min', 'Squad'])

Basic_GK_df

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Player,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%
0,Julen Agirrezabala,es La Liga,66.7,0,0,0
1,Alisson,eng Premier League,73.4,0,0,0.0
2,Alphonse Areola,eng Premier League,74.5,2,0,28.6
3,Simone Aresti,it Serie A,100.0,0,0,0.0
4,Kepa Arrizabalaga,es La Liga,76.3,0,0,0
...,...,...,...,...,...,...
206,Iván Villar,es La Liga,63.6,1,0,33.3
207,Player,Comp,Save%,PKsv,PKm,Save%
208,Odisseas Vlachodimos,eng Premier League,50.0,0,0,0.0
209,Robin Zentner,de Bundesliga,64.8,0,1,0.0
210,Michael Zetterer,de Bundesliga,74.2,0,0,0.0

,Player,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%
0,Julen Agirrezabala,es La Liga,66.7,0,0,0
1,Alisson,eng Premier League,73.4,0,0,0.0
2,Alphonse Areola,eng Premier League,74.5,2,0,28.6
3,Simone Aresti,it Serie A,100.0,0,0,0.0
4,Kepa Arrizabalaga,es La Liga,76.3,0,0,0
...,...,...,...,...,...,...
206,Iván Villar,es La Liga,63.6,1,0,33.3
207,Player,Comp,Save%,PKsv,PKm,Save%
208,Odisseas Vlachodimos,eng Premier League,50.0,0,0,0.0
209,Robin Zentner,de Bundesliga,64.8,0,1,0.0
210,Michael Zetterer,de Bundesliga,74.2,0,0,0.0

In [98]:
# FBref advanced Goalkeeper link
# Now repeat the process for advanced Goalkeeping statistics
url_GK_FB = 'https://fbref.com/en/comps/Big5/2023-2024/keepersadv/players/2023-2024-Big-5-European-Leagues-Stats'

GK_FB = pd.read_html(url_GK_FB)[0]
GK_FB.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Title: 2023-2024 Big 5 European Leagues: Advanced Goalkeeping.
# Author: FBref
# Date: 2024
# Code Version: N/A
# Source: "https://fbref.com/en/comps/Big5/2023-2024/keepersadv/players/2023-2024-Big-5-European-Leagues-Stats"

  Unnamed: 0_level_0  Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk              Player             Nation
0                  1  Julen Agirrezabala             es ESP
1                  2             Alisson             br BRA
2                  3     Alphonse Areola             fr FRA
3                  4       Simone Aresti             it ITA
4                  5   Kepa Arrizabalaga             es ESP

  Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                 Pos              Squad                Comp
0                 GK      Athletic Club          es La Liga
1                 GK          Liverpool  eng Premier League
2                 GK           West Ham  eng Premier League
3                 GK           Cagliari          it Serie A
4                 GK        Real Madrid          es La Liga

  Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Goals  ...  \
                 Age               Born                90s    GA  ...
0                 22               2000                2.6     4  ...
1                 30               1992               28.0    30  ...
2                 30               1993               30.0    53  ...
3                 37               1986                0.0     1  ...
4                 28               1994               13.3     9  ...

  Goal Kicks                Crosses          Sweeper                  \
         Att Launch% AvgLen     Opp Stp Stp%    #OPA #OPA/90 AvgDist
0         22    95.5   64.5      41   2  4.9       3    1.13    15.3
1        116    33.6   33.3     299  13  4.3      33    1.18    17.7
2        219    67.6   47.3     468  27  5.8       7    0.23     8.9
3          0     NaN    NaN       3   0  0.0       0    0.00     NaN
4         70    25.7   30.6     157   6  3.8      10    0.75    14.7

  Unnamed: 34_level_0
              Matches
0             Matches
1             Matches
2             Matches
3             Matches
4             Matches

[5 rows x 35 columns]

  Unnamed: 0_level_0  Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk              Player             Nation
0                  1  Julen Agirrezabala             es ESP
1                  2             Alisson             br BRA
2                  3     Alphonse Areola             fr FRA
3                  4       Simone Aresti             it ITA
4                  5   Kepa Arrizabalaga             es ESP

  Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                 Pos              Squad                Comp
0                 GK      Athletic Club          es La Liga
1                 GK          Liverpool  eng Premier League
2                 GK           West Ham  eng Premier League
3                 GK           Cagliari          it Serie A
4                 GK        Real Madrid          es La Liga

  Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Goals  ...  \
                 Age               Born                90s    GA  ...
0                 22               2000                2.6     4  ...
1                 30               1992               28.0    30  ...
2                 30               1993               30.0    53  ...
3                 37               1986                0.0     1  ...
4                 28               1994               13.3     9  ...

  Goal Kicks                Crosses          Sweeper                  \
         Att Launch% AvgLen     Opp Stp Stp%    #OPA #OPA/90 AvgDist
0         22    95.5   64.5      41   2  4.9       3    1.13    15.3
1        116    33.6   33.3     299  13  4.3      33    1.18    17.7
2        219    67.6   47.3     468  27  5.8       7    0.23     8.9
3          0     NaN    NaN       3   0  0.0       0    0.00     NaN
4         70    25.7   30.6     157   6  3.8      10    0.75    14.7

  Unnamed: 34_level_0
              Matches
0             Matches
1             Matches
2             Matches
3             Matches
4             Matches

[5 rows x 35 columns]

In [99]:
GK_FB.columns = [' '.join(col_GK).strip() for col_GK in GK_FB.columns]

GK_FB = GK_FB.reset_index(drop=True)
GK_FB.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Goals GA,...,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Unnamed: 34_level_0 Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,2.6,4,...,22,95.5,64.5,41,2,4.9,3,1.13,15.3,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28.0,30,...,116,33.6,33.3,299,13,4.3,33,1.18,17.7,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,30.0,53,...,219,67.6,47.3,468,27,5.8,7,0.23,8.9,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,0.0,1,...,0,NaN,NaN,3,0,0.0,0,0.00,NaN,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,13.3,9,...,70,25.7,30.6,157,6,3.8,10,0.75,14.7,Matches

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Player,Unnamed: 2_level_0 Nation,Unnamed: 3_level_0 Pos,Unnamed: 4_level_0 Squad,Unnamed: 5_level_0 Comp,Unnamed: 6_level_0 Age,Unnamed: 7_level_0 Born,Unnamed: 8_level_0 90s,Goals GA,...,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Unnamed: 34_level_0 Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,2.6,4,...,22,95.5,64.5,41,2,4.9,3,1.13,15.3,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28.0,30,...,116,33.6,33.3,299,13,4.3,33,1.18,17.7,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,30.0,53,...,219,67.6,47.3,468,27,5.8,7,0.23,8.9,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,0.0,1,...,0,NaN,NaN,3,0,0.0,0,0.00,NaN,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,13.3,9,...,70,25.7,30.6,157,6,3.8,10,0.75,14.7,Matches

In [100]:
new_col_GK = []
for new_GK in GK_FB.columns:
    if 'level_0' in new_GK:
        new_col_name_GK = new_GK.split()[-1]
        new_col_GK.append(new_col_name_GK)  
    else:
        new_col_GK.append(new_GK)  

GK_FB.columns = new_col_GK
GK_FB = GK_FB.fillna(0)

GK_FB.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Author: Open AI
# Date: 2024
# Source: ChatGPT [online] "https://chat.openai.com/"

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Goals GA,...,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,2.6,4,...,22,95.5,64.5,41,2,4.9,3,1.13,15.3,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28.0,30,...,116,33.6,33.3,299,13,4.3,33,1.18,17.7,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,30.0,53,...,219,67.6,47.3,468,27,5.8,7,0.23,8.9,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,0.0,1,...,0,0,0,3,0,0.0,0,0.00,0,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,13.3,9,...,70,25.7,30.6,157,6,3.8,10,0.75,14.7,Matches

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Goals GA,...,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches
0,1,Julen Agirrezabala,es ESP,GK,Athletic Club,es La Liga,22,2000,2.6,4,...,22,95.5,64.5,41,2,4.9,3,1.13,15.3,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,30,1992,28.0,30,...,116,33.6,33.3,299,13,4.3,33,1.18,17.7,Matches
2,3,Alphonse Areola,fr FRA,GK,West Ham,eng Premier League,30,1993,30.0,53,...,219,67.6,47.3,468,27,5.8,7,0.23,8.9,Matches
3,4,Simone Aresti,it ITA,GK,Cagliari,it Serie A,37,1986,0.0,1,...,0,0,0,3,0,0.0,0,0.00,0,Matches
4,5,Kepa Arrizabalaga,es ESP,GK,Real Madrid,es La Liga,28,1994,13.3,9,...,70,25.7,30.6,157,6,3.8,10,0.75,14.7,Matches

In [101]:
# Dropping columns that are not needed 
GK_FB_df_1 = GK_FB.drop(columns=['Goals GA', 'Rk', 'Goals PKA', 'Born', 'Goals FK', 'Goals CK', 'Comp', 'Goals OG', '90s',
                                'Expected PSxG', 'Expected PSxG/SoT', 'Launched Cmp', 'Launched Att'])

GK_FB_df_1

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Player,Nation,Pos,Squad,Age,Expected PSxG+/-,Expected /90,Launched Cmp%,Passes Att (GK),Passes Thr,...,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches
0,Julen Agirrezabala,es ESP,GK,Athletic Club,22,-1.6,-0.61,36.7,78,20,...,22,95.5,64.5,41,2,4.9,3,1.13,15.3,Matches
1,Alisson,br BRA,GK,Liverpool,30,-0.3,-0.01,32.8,1021,140,...,116,33.6,33.3,299,13,4.3,33,1.18,17.7,Matches
2,Alphonse Areola,fr FRA,GK,West Ham,30,+2.1,+0.07,37.2,643,144,...,219,67.6,47.3,468,27,5.8,7,0.23,8.9,Matches
3,Simone Aresti,it ITA,GK,Cagliari,37,0.0,-1.21,0.0,1,0,...,0,0,0,3,0,0.0,0,0.00,0,Matches
4,Kepa Arrizabalaga,es ESP,GK,Real Madrid,28,+2.0,+0.15,37.0,386,57,...,70,25.7,30.6,157,6,3.8,10,0.75,14.7,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Iván Villar,es ESP,GK,Celta Vigo,26,-0.7,-0.07,28.3,223,48,...,98,60.2,45.7,136,5,3.7,9,0.80,13.2,Matches
207,Player,Nation,Pos,Squad,Age,PSxG+/-,/90,Cmp%,Att (GK),Thr,...,Att,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist,Matches
208,Odisseas Vlachodimos,gr GRE,GK,Nott'ham Forest,29,-4.1,-0.83,46.7,130,21,...,44,61.4,44.3,92,3,3.3,2,0.40,10.3,Matches
209,Robin Zentner,de GER,GK,Mainz 05,28,+2.2,+0.07,35.2,862,146,...,177,58.8,46.4,393,42,10.7,48,1.60,16.0,Matches
210,Michael Zetterer,de GER,GK,Werder Bremen,28,+5.0,+0.18,43.9,977,161,...,144,36.1,38.1,407,34,8.4,30,1.11,14.6,Matches

,Player,Nation,Pos,Squad,Age,Expected PSxG+/-,Expected /90,Launched Cmp%,Passes Att (GK),Passes Thr,...,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches
0,Julen Agirrezabala,es ESP,GK,Athletic Club,22,-1.6,-0.61,36.7,78,20,...,22,95.5,64.5,41,2,4.9,3,1.13,15.3,Matches
1,Alisson,br BRA,GK,Liverpool,30,-0.3,-0.01,32.8,1021,140,...,116,33.6,33.3,299,13,4.3,33,1.18,17.7,Matches
2,Alphonse Areola,fr FRA,GK,West Ham,30,+2.1,+0.07,37.2,643,144,...,219,67.6,47.3,468,27,5.8,7,0.23,8.9,Matches
3,Simone Aresti,it ITA,GK,Cagliari,37,0.0,-1.21,0.0,1,0,...,0,0,0,3,0,0.0,0,0.00,0,Matches
4,Kepa Arrizabalaga,es ESP,GK,Real Madrid,28,+2.0,+0.15,37.0,386,57,...,70,25.7,30.6,157,6,3.8,10,0.75,14.7,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Iván Villar,es ESP,GK,Celta Vigo,26,-0.7,-0.07,28.3,223,48,...,98,60.2,45.7,136,5,3.7,9,0.80,13.2,Matches
207,Player,Nation,Pos,Squad,Age,PSxG+/-,/90,Cmp%,Att (GK),Thr,...,Att,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist,Matches
208,Odisseas Vlachodimos,gr GRE,GK,Nott'ham Forest,29,-4.1,-0.83,46.7,130,21,...,44,61.4,44.3,92,3,3.3,2,0.40,10.3,Matches
209,Robin Zentner,de GER,GK,Mainz 05,28,+2.2,+0.07,35.2,862,146,...,177,58.8,46.4,393,42,10.7,48,1.60,16.0,Matches
210,Michael Zetterer,de GER,GK,Werder Bremen,28,+5.0,+0.18,43.9,977,161,...,144,36.1,38.1,407,34,8.4,30,1.11,14.6,Matches

In [102]:
# Outer join in python pandas to create on dataset for outfield players (players that are not goalkeepers)
# This will merge the datasets together using the outer join method based on players 
# This is done so they have all the desired standard, defensive and other relevant data

# Merge the datasets in steps and remove duplicates at each step
first_df = pd.merge(df_FB, df_FB_POSS, on='Player', how='outer').drop_duplicates(subset=['Player'], keep='first')
second_df = pd.merge(df_FB_Other, first_df, on='Player', how='outer').drop_duplicates(subset=['Player'], keep='first')
Oj_df = pd.merge(second_df, df_FB_DEF, on='Player', how='outer').drop_duplicates(subset=['Player'], keep='first')

# Adapted From:
# Title: Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python
# Author: Sridhar Venkatachalam
# Date: No date
# Code Version: N/A
# Source: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/""

# Adapted From:
# Title: Python | Pandas dataframe.drop_duplicates()
# Author: Geeks for Geeks
# Date: 2024
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/"

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

In [103]:
# Outer join in python pandas for goalkeepers
# Goalkeepers have a very specialised skillset, thus have different stats to measure their performance

# Merge the two goalkeeper datasets and remove the duplicate rows
Oj_df_GK = pd.merge(GK_FB_df_1, Basic_GK_df, on='Player', how='outer').drop_duplicates(subset=['Player'], keep='first')

# Adapted From:
# Title: Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python
# Author: Sridhar Venkatachalam
# Date: No date
# Code Version: N/A
# Source: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/""

# Adapted From:
# Title: Python | Pandas dataframe.drop_duplicates()
# Author: Geeks for Geeks
# Date: 2024
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/"

In [104]:
full_FB_dataset = Oj_df
# A very important player in the later stages of the project called "Rodri" shares his name with a less important player
# The less important "Rodri" is removed
full_FB_dataset = full_FB_dataset.drop(index=24)

# Some important players for the performance rating have different name spellings in the FBref and Transfermarkt dataset
# Their names will be manually changed to match in the datasets
# Thus their names are now the same across the Fbref and Transfermarkt data 
full_FB_dataset['Player'] = full_FB_dataset['Player'].replace('Jeremy Doku', 'Jérémy Doku')
full_FB_dataset['Player'] = full_FB_dataset['Player'].replace('Son Heung-min', 'Heung-min Son')
full_FB_dataset['Player'] = full_FB_dataset['Player'].replace('Álex Grimaldo', 'Alejandro Grimaldo')
full_FB_dataset['Player'] = full_FB_dataset['Player'].replace('Luka Modric', 'Luka Modrić')

# Adapted From:
# Title: pandas.DataFrame.drop
# Author: Pandas
# Date: No date
# Code Version: 2.2
# Source: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html"

# Adapted From:
# Title: pandas.DataFrame.replace
# Author: Pandas
# Date: No date
# Code Version: 2.2
# Source: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html"

In [105]:
full_FB_dataset['Player_1'] = full_FB_dataset['Player']

In [106]:
# Transfermarkt Dataset

In [107]:
d_player = pd.read_csv("players.csv", encoding='utf-8-sig')
df_player = pd.DataFrame(d_player)

# Title: ‘Football Data from Transfermarkt’
# Author: Cariboo, D.
# Date: 2024
# Code Version: N/A
# Source: "https://www.kaggle.com/datasets/davidcariboo/player-scores/data"

In [108]:
# This is to stop the character from changing when saving it as a CSV, i.e., stop Mbappé becoming MbappÃ©. 

# Save the Tranfermarkt DataFrame to a CSV file with the utf-8-sig encoding
df_player.to_csv('file120.csv', encoding='utf-8-sig', index=False)

In [109]:
# Data is loaded with correct player names
d_player_1 = pd.read_csv("file120.csv")
df_player_1 = pd.DataFrame(d_player_1)

In [110]:
df_player_1.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [111]:
# Dropping columns in transfermarkt dataset that are not needed 
full_df = df_player_1.drop(columns=['first_name', 'player_id', 'current_club_id', 'last_season', 'city_of_birth', 'last_name', 
                              'image_url', 'url', 'current_club_domestic_competition_id'])
full_df = full_df.drop(index=0)
full_df ['foot'] = full_df['foot'].fillna('NA')
full_df ['height_in_cm'] = full_df['height_in_cm'].fillna('NA')
full_df ['contract_expiration_date'] = full_df['contract_expiration_date'].fillna('NA')
full_df ['agent_name'] = full_df['agent_name'].fillna('NA')
full_df = full_df.drop(index=753) # Gets rid of duplicate "Rodri"
full_df

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Title: pandas.DataFrame.drop
# Author: Pandas
# Date: No date
# Code Version: 2.2
# Source: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html"

# Adapted From:
# Title: pandas.DataFrame.replace
# Author: Pandas
# Date: No date
# Code Version: 2.2
# Source: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html"

,name,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur
1,Roman Weidenfeller,roman-weidenfeller,Germany,Germany,1980-08-06,Goalkeeper,Goalkeeper,left,190.0,NA,Neubauer 13 GmbH,Borussia Dortmund,750000.0,8000000.0
2,Dimitar Berbatov,dimitar-berbatov,Bulgaria,Bulgaria,1981-01-30,Centre-Forward,Attack,NA,NA,NA,CSKA-AS-23 Ltd.,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,Lúcio,lucio,Brazil,Brazil,1978-05-08,Centre-Back,Defender,NA,NA,NA,NA,Juventus Football Club,200000.0,24500000.0
4,Tom Starke,tom-starke,East Germany (GDR),Germany,1981-03-18,Goalkeeper,Goalkeeper,right,194.0,NA,IFM,FC Bayern München,100000.0,3000000.0
5,Dedê,dede,Brazil,Brazil,1978-04-18,Left-Back,Defender,NA,NA,NA,Football Concept,Eskisehirspor,400000.0,9500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30515,Sid Ahmed Aissaoui,sid-ahmed-aissaoui,Algeria,Algeria,2005-01-11,Central Midfield,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0
30516,Erdem Çalık,erdem-calik,Türkiye,Türkiye,2006-06-05,Central Midfield,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0
30517,Adama Sidibeh,adama-sidibeh,NaN,The Gambia,1998-06-25,Centre-Forward,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN
30518,Artem Prysyazhnyuk,artem-prysyazhnyuk,Ukraine,Ukraine,2005-07-17,Central Midfield,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN
30519,Araphat Mohammed,araphat-mohammed,NaN,Ghana,2005-11-06,Central Midfield,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN

,name,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur
1,Roman Weidenfeller,roman-weidenfeller,Germany,Germany,1980-08-06,Goalkeeper,Goalkeeper,left,190.0,NA,Neubauer 13 GmbH,Borussia Dortmund,750000.0,8000000.0
2,Dimitar Berbatov,dimitar-berbatov,Bulgaria,Bulgaria,1981-01-30,Centre-Forward,Attack,NA,NA,NA,CSKA-AS-23 Ltd.,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,Lúcio,lucio,Brazil,Brazil,1978-05-08,Centre-Back,Defender,NA,NA,NA,NA,Juventus Football Club,200000.0,24500000.0
4,Tom Starke,tom-starke,East Germany (GDR),Germany,1981-03-18,Goalkeeper,Goalkeeper,right,194.0,NA,IFM,FC Bayern München,100000.0,3000000.0
5,Dedê,dede,Brazil,Brazil,1978-04-18,Left-Back,Defender,NA,NA,NA,Football Concept,Eskisehirspor,400000.0,9500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30515,Sid Ahmed Aissaoui,sid-ahmed-aissaoui,Algeria,Algeria,2005-01-11,Central Midfield,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0
30516,Erdem Çalık,erdem-calik,Türkiye,Türkiye,2006-06-05,Central Midfield,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0
30517,Adama Sidibeh,adama-sidibeh,NaN,The Gambia,1998-06-25,Centre-Forward,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN
30518,Artem Prysyazhnyuk,artem-prysyazhnyuk,Ukraine,Ukraine,2005-07-17,Central Midfield,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN
30519,Araphat Mohammed,araphat-mohammed,NaN,Ghana,2005-11-06,Central Midfield,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN

In [112]:
# Here is a seperate dataset from the transfermarkt dataset that only has goalkeepers
df_1_GK = full_df[full_df['position'].isin(['Goalkeeper'])]
df_2_GK = df_1_GK.rename(columns={"name": "Player"})
df_2_GK


# Title: Pandas DataFrame isin() Method
# Author: W3 Schools
# Date: No date
# Code Version: N/A
# Source: "https://www.w3schools.com/python/pandas/ref_df_isin.asp"

,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur
1,Roman Weidenfeller,roman-weidenfeller,Germany,Germany,1980-08-06,Goalkeeper,Goalkeeper,left,190.0,NA,Neubauer 13 GmbH,Borussia Dortmund,750000.0,8000000.0
4,Tom Starke,tom-starke,East Germany (GDR),Germany,1981-03-18,Goalkeeper,Goalkeeper,right,194.0,NA,IFM,FC Bayern München,100000.0,3000000.0
8,Marc Ziegler,marc-ziegler,Germany,Germany,1976-06-13,Goalkeeper,Goalkeeper,right,193.0,NA,NA,Verein für Bewegungsspiele Stuttgart 1893,200000.0,1250000.0
19,Oka Nikolov,oka-nikolov,Germany,North Macedonia,1974-05-25,Goalkeeper,Goalkeeper,right,188.0,NA,PRO Profil GmbH,Eintracht Frankfurt Fußball AG,350000.0,2000000.0
20,Gerhard Tremmel,gerhard-tremmel,Germany,Germany,1978-11-16,Goalkeeper,Goalkeeper,NA,NA,NA,NA,Swansea City,250000.0,2200000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30476,Pavlo Ripak,pavlo-ripak,NaN,Ukraine,2007-07-09,Goalkeeper,Goalkeeper,NA,184.0,NA,NA,PFK Lviv,NaN,NaN
30485,Luís Pires,luis-pires,NaN,Brazil,2004-11-17,Goalkeeper,Goalkeeper,right,188.0,2024-06-30 00:00:00,ML3 Football,Boavista Futebol Clube,100000.0,100000.0
30492,Siemen Buvé,siemen-buve,NaN,Belgium,2005-01-15,Goalkeeper,Goalkeeper,NA,NA,NA,NA,Koninklijke Sint-Truidense Voetbalvereniging,NaN,NaN
30496,Viktor Dolgyi,viktor-dolgyi,Ukraine,Ukraine,2004-01-02,Goalkeeper,Goalkeeper,left,197.0,2027-06-30 00:00:00,PFA,FK Oleksandriya,50000.0,50000.0
30514,Yusuf Yılmaz,yusuf-yilmaz,Türkiye,Türkiye,2006-04-29,Goalkeeper,Goalkeeper,right,193.0,NA,NA,İstanbul Başakşehir Futbol Kulübü,50000.0,50000.0

,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur
1,Roman Weidenfeller,roman-weidenfeller,Germany,Germany,1980-08-06,Goalkeeper,Goalkeeper,left,190.0,NA,Neubauer 13 GmbH,Borussia Dortmund,750000.0,8000000.0
4,Tom Starke,tom-starke,East Germany (GDR),Germany,1981-03-18,Goalkeeper,Goalkeeper,right,194.0,NA,IFM,FC Bayern München,100000.0,3000000.0
8,Marc Ziegler,marc-ziegler,Germany,Germany,1976-06-13,Goalkeeper,Goalkeeper,right,193.0,NA,NA,Verein für Bewegungsspiele Stuttgart 1893,200000.0,1250000.0
19,Oka Nikolov,oka-nikolov,Germany,North Macedonia,1974-05-25,Goalkeeper,Goalkeeper,right,188.0,NA,PRO Profil GmbH,Eintracht Frankfurt Fußball AG,350000.0,2000000.0
20,Gerhard Tremmel,gerhard-tremmel,Germany,Germany,1978-11-16,Goalkeeper,Goalkeeper,NA,NA,NA,NA,Swansea City,250000.0,2200000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30476,Pavlo Ripak,pavlo-ripak,NaN,Ukraine,2007-07-09,Goalkeeper,Goalkeeper,NA,184.0,NA,NA,PFK Lviv,NaN,NaN
30485,Luís Pires,luis-pires,NaN,Brazil,2004-11-17,Goalkeeper,Goalkeeper,right,188.0,2024-06-30 00:00:00,ML3 Football,Boavista Futebol Clube,100000.0,100000.0
30492,Siemen Buvé,siemen-buve,NaN,Belgium,2005-01-15,Goalkeeper,Goalkeeper,NA,NA,NA,NA,Koninklijke Sint-Truidense Voetbalvereniging,NaN,NaN
30496,Viktor Dolgyi,viktor-dolgyi,Ukraine,Ukraine,2004-01-02,Goalkeeper,Goalkeeper,left,197.0,2027-06-30 00:00:00,PFA,FK Oleksandriya,50000.0,50000.0
30514,Yusuf Yılmaz,yusuf-yilmaz,Türkiye,Türkiye,2006-04-29,Goalkeeper,Goalkeeper,right,193.0,NA,NA,İstanbul Başakşehir Futbol Kulübü,50000.0,50000.0

In [113]:
# Renames the name column to player to allow for merging of datasets
full_df_1 = full_df.rename(columns={"name": "Player"})

In [114]:
# Outer join in python pandas to merge the FBref and Transfermarkt datasets together
# This is done by the 'Player' variable
 
# Joining outfield players datasets    
Join_True_dataset=full_FB_dataset.merge(full_df_1, on='Player', how='outer')

# Joining Goalkeeper datasets    
Join_GK_dataset=df_2_GK.merge(Oj_df_GK, on='Player', how='outer')

# Remove duplicates based on the 'Player' column (outfield players)
JT_remove_duplicates = Join_True_dataset.drop_duplicates(subset=['Player'], keep='first')
True_dataset = JT_remove_duplicates.reset_index(drop=True)
True_dataset

# Remove duplicates based on the 'Player' column (Goalkeepers)
JT_remove_duplicates_GK = Join_GK_dataset.drop_duplicates(subset=['Player'], keep='first')
True_dataset_GK = JT_remove_duplicates_GK.reset_index(drop=True)

# Transfermarkt has more rows than FBref as it is more than just top 5 leagues
# Thus why so many rows of player with limited data
True_dataset_GK



# Adapted From:
# Title: Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python
# Author: Sridhar Venkatachalam
# Date: No date
# Code Version: N/A
# Source: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/""

# Adapted From:
# Title: Python | Pandas dataframe.drop_duplicates()
# Author: Geeks for Geeks
# Date: 2024
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/"

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,...,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%
0,Roman Weidenfeller,roman-weidenfeller,Germany,Germany,1980-08-06,Goalkeeper,Goalkeeper,left,190.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tom Starke,tom-starke,East Germany (GDR),Germany,1981-03-18,Goalkeeper,Goalkeeper,right,194.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Marc Ziegler,marc-ziegler,Germany,Germany,1976-06-13,Goalkeeper,Goalkeeper,right,193.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Oka Nikolov,oka-nikolov,Germany,North Macedonia,1974-05-25,Goalkeeper,Goalkeeper,right,188.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gerhard Tremmel,gerhard-tremmel,Germany,Germany,1978-11-16,Goalkeeper,Goalkeeper,NA,NA,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513,Predrag Rajković,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.6,28,0.78,13.7,Matches,es La Liga,71.7,1,0,20.0
3514,Frederik Rønnow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,37,1.12,12.9,Matches,de Bundesliga,68.5,2,0,28.6
3515,Łukasz Skorupski,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8,15,0.47,12.2,Matches,it Serie A,75.5,1,2,25.0
3516,Álvaro Vallés,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.6,96,2.65,17.8,Matches,es La Liga,74.3,3,1,37.5
3517,Odisseas Vlachodimos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.3,2,0.40,10.3,Matches,eng Premier League,50.0,0,0,0.0

,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,...,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%
0,Roman Weidenfeller,roman-weidenfeller,Germany,Germany,1980-08-06,Goalkeeper,Goalkeeper,left,190.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tom Starke,tom-starke,East Germany (GDR),Germany,1981-03-18,Goalkeeper,Goalkeeper,right,194.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Marc Ziegler,marc-ziegler,Germany,Germany,1976-06-13,Goalkeeper,Goalkeeper,right,193.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Oka Nikolov,oka-nikolov,Germany,North Macedonia,1974-05-25,Goalkeeper,Goalkeeper,right,188.0,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Gerhard Tremmel,gerhard-tremmel,Germany,Germany,1978-11-16,Goalkeeper,Goalkeeper,NA,NA,NA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513,Predrag Rajković,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.6,28,0.78,13.7,Matches,es La Liga,71.7,1,0,20.0
3514,Frederik Rønnow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,37,1.12,12.9,Matches,de Bundesliga,68.5,2,0,28.6
3515,Łukasz Skorupski,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8,15,0.47,12.2,Matches,it Serie A,75.5,1,2,25.0
3516,Álvaro Vallés,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.6,96,2.65,17.8,Matches,es La Liga,74.3,3,1,37.5
3517,Odisseas Vlachodimos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.3,2,0.40,10.3,Matches,eng Premier League,50.0,0,0,0.0

In [115]:
# Feature Engineering

In [116]:
# FBref link, repeat early process of webscrapping 
# This data will be extracted and provide variables that will allow for Feature Engineering
url_df_SQ = 'https://fbref.com/en/comps/Big5/2023-2024/possession/squads/2023-2024-Big-5-European-Leagues-Stats'

df_SQ = pd.read_html(url_df_SQ)[0]
df_SQ.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Title: 2023-2024 Big 5 European Leagues: Possession (Squad)
# Author: FBref
# Date: 2024
# Code Version: N/A
# Source: "https://fbref.com/en/comps/Big5/2023-2024/possession/squads/2023-2024-Big-5-European-Leagues-Stats"

  Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                  Rk              Squad                Comp
0                  1             Alavés          es La Liga
1                  2            Almería          es La Liga
2                  3            Arsenal  eng Premier League
3                  4        Aston Villa  eng Premier League
4                  5           Atalanta          it Serie A

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Touches          \
                # Pl               Poss                90s Touches Def Pen
0                 30               41.8               38.0   18179    2162
1                 35               46.4               38.0   20902    2654
2                 25               58.2               38.0   26493    1974
3                 31               53.1               38.0   23058    2807
4                 29               51.1               38.0   24136    2222

                   ... Carries                                           \
  Def 3rd Mid 3rd  ... Carries TotDist PrgDist PrgC  1/3  CPA  Mis  Dis
0    6122    7564  ...    8574   48049   25494  550  364  138  572  299
1    7711    9323  ...   11128   59196   30444  590  424  132  550  269
2    6714   11407  ...   16297   81171   41510  821  575  327  525  375
3    8170    9636  ...   14450   78599   41219  775  490  217  477  416
4    7494   10658  ...   13093   68816   34111  715  519  175  621  377

  Receiving
        Rec  PrgR
0      9972  1252
1     12660  1082
2     18917  2088
3     15823  1438
4     15915  1733

[5 rows x 28 columns]

  Unnamed: 0_level_0 Unnamed: 1_level_0  Unnamed: 2_level_0  \
                  Rk              Squad                Comp
0                  1             Alavés          es La Liga
1                  2            Almería          es La Liga
2                  3            Arsenal  eng Premier League
3                  4        Aston Villa  eng Premier League
4                  5           Atalanta          it Serie A

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Touches          \
                # Pl               Poss                90s Touches Def Pen
0                 30               41.8               38.0   18179    2162
1                 35               46.4               38.0   20902    2654
2                 25               58.2               38.0   26493    1974
3                 31               53.1               38.0   23058    2807
4                 29               51.1               38.0   24136    2222

                   ... Carries                                           \
  Def 3rd Mid 3rd  ... Carries TotDist PrgDist PrgC  1/3  CPA  Mis  Dis
0    6122    7564  ...    8574   48049   25494  550  364  138  572  299
1    7711    9323  ...   11128   59196   30444  590  424  132  550  269
2    6714   11407  ...   16297   81171   41510  821  575  327  525  375
3    8170    9636  ...   14450   78599   41219  775  490  217  477  416
4    7494   10658  ...   13093   68816   34111  715  519  175  621  377

  Receiving
        Rec  PrgR
0      9972  1252
1     12660  1082
2     18917  2088
3     15823  1438
4     15915  1733

[5 rows x 28 columns]

In [117]:
df_SQ.columns = [' '.join(col_SQ).strip() for col_SQ in df_SQ.columns]

df_SQ = df_SQ.reset_index(drop=True)
df_SQ.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Squad,Unnamed: 2_level_0 Comp,Unnamed: 3_level_0 # Pl,Unnamed: 4_level_0 Poss,Unnamed: 5_level_0 90s,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,...,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR
0,1,Alavés,es La Liga,30,41.8,38.0,18179,2162,6122,7564,...,8574,48049,25494,550,364,138,572,299,9972,1252
1,2,Almería,es La Liga,35,46.4,38.0,20902,2654,7711,9323,...,11128,59196,30444,590,424,132,550,269,12660,1082
2,3,Arsenal,eng Premier League,25,58.2,38.0,26493,1974,6714,11407,...,16297,81171,41510,821,575,327,525,375,18917,2088
3,4,Aston Villa,eng Premier League,31,53.1,38.0,23058,2807,8170,9636,...,14450,78599,41219,775,490,217,477,416,15823,1438
4,5,Atalanta,it Serie A,29,51.1,38.0,24136,2222,7494,10658,...,13093,68816,34111,715,519,175,621,377,15915,1733

,Unnamed: 0_level_0 Rk,Unnamed: 1_level_0 Squad,Unnamed: 2_level_0 Comp,Unnamed: 3_level_0 # Pl,Unnamed: 4_level_0 Poss,Unnamed: 5_level_0 90s,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,...,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR
0,1,Alavés,es La Liga,30,41.8,38.0,18179,2162,6122,7564,...,8574,48049,25494,550,364,138,572,299,9972,1252
1,2,Almería,es La Liga,35,46.4,38.0,20902,2654,7711,9323,...,11128,59196,30444,590,424,132,550,269,12660,1082
2,3,Arsenal,eng Premier League,25,58.2,38.0,26493,1974,6714,11407,...,16297,81171,41510,821,575,327,525,375,18917,2088
3,4,Aston Villa,eng Premier League,31,53.1,38.0,23058,2807,8170,9636,...,14450,78599,41219,775,490,217,477,416,15823,1438
4,5,Atalanta,it Serie A,29,51.1,38.0,24136,2222,7494,10658,...,13093,68816,34111,715,519,175,621,377,15915,1733

In [118]:
new_col_SQ = []
for new_SQ in df_SQ.columns:
    if 'level_0' in new_SQ:
        new_col_name_SQ = new_SQ.split()[-1]
        new_col_SQ.append(new_col_name_SQ)  
    else:
        new_col_SQ.append(new_SQ)  

df_SQ.columns = new_col_SQ
df_SQ = df_SQ.fillna(0)

df_SQ.head()

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Author: Open AI
# Date: 2024
# Source: ChatGPT [online] "https://chat.openai.com/"

,Rk,Squad,Comp,Pl,Poss,90s,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,...,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR
0,1,Alavés,es La Liga,30,41.8,38.0,18179,2162,6122,7564,...,8574,48049,25494,550,364,138,572,299,9972,1252
1,2,Almería,es La Liga,35,46.4,38.0,20902,2654,7711,9323,...,11128,59196,30444,590,424,132,550,269,12660,1082
2,3,Arsenal,eng Premier League,25,58.2,38.0,26493,1974,6714,11407,...,16297,81171,41510,821,575,327,525,375,18917,2088
3,4,Aston Villa,eng Premier League,31,53.1,38.0,23058,2807,8170,9636,...,14450,78599,41219,775,490,217,477,416,15823,1438
4,5,Atalanta,it Serie A,29,51.1,38.0,24136,2222,7494,10658,...,13093,68816,34111,715,519,175,621,377,15915,1733

,Rk,Squad,Comp,Pl,Poss,90s,Touches Touches,Touches Def Pen,Touches Def 3rd,Touches Mid 3rd,...,Carries Carries,Carries TotDist,Carries PrgDist,Carries PrgC,Carries 1/3,Carries CPA,Carries Mis,Carries Dis,Receiving Rec,Receiving PrgR
0,1,Alavés,es La Liga,30,41.8,38.0,18179,2162,6122,7564,...,8574,48049,25494,550,364,138,572,299,9972,1252
1,2,Almería,es La Liga,35,46.4,38.0,20902,2654,7711,9323,...,11128,59196,30444,590,424,132,550,269,12660,1082
2,3,Arsenal,eng Premier League,25,58.2,38.0,26493,1974,6714,11407,...,16297,81171,41510,821,575,327,525,375,18917,2088
3,4,Aston Villa,eng Premier League,31,53.1,38.0,23058,2807,8170,9636,...,14450,78599,41219,775,490,217,477,416,15823,1438
4,5,Atalanta,it Serie A,29,51.1,38.0,24136,2222,7494,10658,...,13093,68816,34111,715,519,175,621,377,15915,1733

In [119]:
# These columns are not needed for the feature engineering 
df_SQ_1 = df_SQ.drop(columns=['Touches Def Pen', 'Touches Def 3rd', 'Touches Mid 3rd', 'Touches Att 3rd', 
                              'Touches Att Pen', 'Touches Live', 'Take-Ons Att', 'Take-Ons Succ', 'Take-Ons Succ%',
                             'Take-Ons Tkld', 'Take-Ons Tkld%', 'Carries Carries', 'Carries TotDist',
                              'Carries PrgDist', 'Carries PrgC', 'Carries 1/3', 'Carries CPA', 'Carries Mis',
                              'Carries Dis', 'Receiving Rec', 'Receiving PrgR', 'Comp', 'Rk', 'Pl'])
df_SQ_1

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

            Squad  Poss   90s  Touches Touches
0          Alavés  41.8  38.0            18179
1         Almería  46.4  38.0            20902
2         Arsenal  58.2  38.0            26493
3     Aston Villa  53.1  38.0            23058
4        Atalanta  51.1  38.0            24136
..            ...   ...   ...              ...
91     Villarreal  49.6  38.0            22729
92  Werder Bremen  46.8  34.0            20347
93       West Ham  41.1  38.0            20875
94      Wolfsburg  48.0  34.0            20363
95         Wolves  48.9  38.0            23485

[96 rows x 4 columns]

            Squad  Poss   90s  Touches Touches
0          Alavés  41.8  38.0            18179
1         Almería  46.4  38.0            20902
2         Arsenal  58.2  38.0            26493
3     Aston Villa  53.1  38.0            23058
4        Atalanta  51.1  38.0            24136
..            ...   ...   ...              ...
91     Villarreal  49.6  38.0            22729
92  Werder Bremen  46.8  34.0            20347
93       West Ham  41.1  38.0            20875
94      Wolfsburg  48.0  34.0            20363
95         Wolves  48.9  38.0            23485

[96 rows x 4 columns]

In [120]:
True_dataset.rename(columns = {'Squad_x':'Squad'}, inplace = True)

# Adapted From:
# Title: How to Rename Pandas DataFrame Columns (with Examples)
# Author: datagy
# Date: 2021
# Code Version: N/A
# Source: "https://datagy.io/rename-pandas-columns/"

In [121]:
# Merge the complete dataset from earlier and the one needed for feature engineering
newest_dt=df_SQ_1.merge(True_dataset, on='Squad', how='outer')
newest_dt

# Adapted From:
# Title: Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python
# Author: Sridhar Venkatachalam
# Date: No date
# Code Version: N/A
# Source: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/"

# Adapted From:
# Title: Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python
# Author: Sridhar Venkatachalam
# Date: No date
# Code Version: N/A
# Source: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/""

# Adapted From:
# Title: Python | Pandas dataframe.drop_duplicates()
# Author: Geeks for Geeks
# Date: 2024
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/"

,Squad,Poss,90s_x,Touches Touches_x,Player,Performance Fls,Performance Fld,Performance Off,Performance Crs,Performance PKwon,...,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,Alavés,41.8,38.0,18179.0,Abdel Abqar,33,23,1,2,0,...,1999-03-10,Centre-Back,Defender,right,188.0,2025-06-30 00:00:00,11MANGMT,Deportivo Alavés S.A.D.,3000000.0,3000000.0
1,Alavés,41.8,38.0,18179.0,Carlos Benavídez,38,9,1,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alavés,41.8,38.0,18179.0,Antonio Blanco,36,40,0,15,0,...,2000-07-23,Defensive Midfield,Midfield,right,176.0,2027-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,5000000.0,5000000.0
3,Alavés,41.8,38.0,18179.0,Rubén Duarte,31,30,0,70,0,...,1995-10-18,Left-Back,Defender,left,179.0,2026-06-30 00:00:00,CAA Stellar,Deportivo Alavés S.A.D.,2500000.0,6000000.0
4,Alavés,41.8,38.0,18179.0,Andoni Gorosabel,29,41,0,81,1,...,1996-08-04,Right-Back,Defender,right,174.0,2024-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,2500000.0,10000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30321,NaN,NaN,NaN,NaN,Sid Ahmed Aissaoui,NaN,NaN,NaN,NaN,NaN,...,2005-01-11,Central Midfield,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0
30322,NaN,NaN,NaN,NaN,Erdem Çalık,NaN,NaN,NaN,NaN,NaN,...,2006-06-05,Central Midfield,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0
30323,NaN,NaN,NaN,NaN,Adama Sidibeh,NaN,NaN,NaN,NaN,NaN,...,1998-06-25,Centre-Forward,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN
30324,NaN,NaN,NaN,NaN,Artem Prysyazhnyuk,NaN,NaN,NaN,NaN,NaN,...,2005-07-17,Central Midfield,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN
30325,NaN,NaN,NaN,NaN,Araphat Mohammed,NaN,NaN,NaN,NaN,NaN,...,2005-11-06,Central Midfield,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN

,Squad,Poss,90s_x,Touches Touches_x,Player,Performance Fls,Performance Fld,Performance Off,Performance Crs,Performance PKwon,...,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,Alavés,41.8,38.0,18179.0,Abdel Abqar,33,23,1,2,0,...,1999-03-10,Centre-Back,Defender,right,188.0,2025-06-30 00:00:00,11MANGMT,Deportivo Alavés S.A.D.,3000000.0,3000000.0
1,Alavés,41.8,38.0,18179.0,Carlos Benavídez,38,9,1,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Alavés,41.8,38.0,18179.0,Antonio Blanco,36,40,0,15,0,...,2000-07-23,Defensive Midfield,Midfield,right,176.0,2027-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,5000000.0,5000000.0
3,Alavés,41.8,38.0,18179.0,Rubén Duarte,31,30,0,70,0,...,1995-10-18,Left-Back,Defender,left,179.0,2026-06-30 00:00:00,CAA Stellar,Deportivo Alavés S.A.D.,2500000.0,6000000.0
4,Alavés,41.8,38.0,18179.0,Andoni Gorosabel,29,41,0,81,1,...,1996-08-04,Right-Back,Defender,right,174.0,2024-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,2500000.0,10000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30321,NaN,NaN,NaN,NaN,Sid Ahmed Aissaoui,NaN,NaN,NaN,NaN,NaN,...,2005-01-11,Central Midfield,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0
30322,NaN,NaN,NaN,NaN,Erdem Çalık,NaN,NaN,NaN,NaN,NaN,...,2006-06-05,Central Midfield,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0
30323,NaN,NaN,NaN,NaN,Adama Sidibeh,NaN,NaN,NaN,NaN,NaN,...,1998-06-25,Centre-Forward,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN
30324,NaN,NaN,NaN,NaN,Artem Prysyazhnyuk,NaN,NaN,NaN,NaN,NaN,...,2005-07-17,Central Midfield,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN
30325,NaN,NaN,NaN,NaN,Araphat Mohammed,NaN,NaN,NaN,NaN,NaN,...,2005-11-06,Central Midfield,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN

In [122]:
True_dataset_GK.rename(columns = {'Squad_x':'Squad'}, inplace = True)

In [123]:
# Merge the complete goalkeeper dataset from earlier and the one needed for feature engineering
newest_dt_GK=df_SQ_1.merge(True_dataset_GK, on='Squad', how='outer')
newest_dt_GK

# Adapted From:
# Title: Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python
# Author: Sridhar Venkatachalam
# Date: No date
# Code Version: N/A
# Source: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/""

# Adapted From:
# Title: Python | Pandas dataframe.drop_duplicates()
# Author: Geeks for Geeks
# Date: 2024
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/"

,Squad,Poss,90s,Touches Touches,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%
0,Alavés,41.8,38.0,18179.0,Antonio Sivera,antonio-sivera,Spain,Spain,1996-08-11,Goalkeeper,...,5.0,29,0.85,13.1,Matches,es La Liga,75.6,0,0,0.0
1,Alavés,41.8,38.0,18179.0,Jesús Owono,jesus-owono,Equatorial Guinea,Equatorial Guinea,2001-03-01,Goalkeeper,...,13.8,8,2.00,15.2,Matches,es La Liga,66.7,0,0,0
2,Almería,46.4,38.0,20902.0,Diego Mariño,diego-marino,Spain,Spain,1990-05-09,Goalkeeper,...,0.0,2,2.00,22.7,Matches,es La Liga,100.0,0,0,0.0
3,Almería,46.4,38.0,20902.0,Luís Maximiano,luis-maximiano,Portugal,Portugal,1999-01-05,Goalkeeper,...,4.5,38,1.15,14.5,Matches,es La Liga,66.3,1,2,20.0
4,Almería,46.4,38.0,20902.0,Fernando,NaN,NaN,NaN,NaN,NaN,...,5.6,7,1.75,14.5,Matches,es La Liga,56.5,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513,NaN,NaN,NaN,NaN,Luís Pires,luis-pires,NaN,Brazil,2004-11-17,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3514,NaN,NaN,NaN,NaN,Siemen Buvé,siemen-buve,NaN,Belgium,2005-01-15,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3515,NaN,NaN,NaN,NaN,Viktor Dolgyi,viktor-dolgyi,Ukraine,Ukraine,2004-01-02,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3516,NaN,NaN,NaN,NaN,Yusuf Yılmaz,yusuf-yilmaz,Türkiye,Türkiye,2006-04-29,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3517,Squad,NaN,NaN,NaN,Player,NaN,NaN,NaN,NaN,NaN,...,Stp%,#OPA,#OPA/90,AvgDist,Matches,Comp,Save%,PKsv,PKm,Save%

,Squad,Poss,90s,Touches Touches,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist,Matches,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%
0,Alavés,41.8,38.0,18179.0,Antonio Sivera,antonio-sivera,Spain,Spain,1996-08-11,Goalkeeper,...,5.0,29,0.85,13.1,Matches,es La Liga,75.6,0,0,0.0
1,Alavés,41.8,38.0,18179.0,Jesús Owono,jesus-owono,Equatorial Guinea,Equatorial Guinea,2001-03-01,Goalkeeper,...,13.8,8,2.00,15.2,Matches,es La Liga,66.7,0,0,0
2,Almería,46.4,38.0,20902.0,Diego Mariño,diego-marino,Spain,Spain,1990-05-09,Goalkeeper,...,0.0,2,2.00,22.7,Matches,es La Liga,100.0,0,0,0.0
3,Almería,46.4,38.0,20902.0,Luís Maximiano,luis-maximiano,Portugal,Portugal,1999-01-05,Goalkeeper,...,4.5,38,1.15,14.5,Matches,es La Liga,66.3,1,2,20.0
4,Almería,46.4,38.0,20902.0,Fernando,NaN,NaN,NaN,NaN,NaN,...,5.6,7,1.75,14.5,Matches,es La Liga,56.5,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513,NaN,NaN,NaN,NaN,Luís Pires,luis-pires,NaN,Brazil,2004-11-17,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3514,NaN,NaN,NaN,NaN,Siemen Buvé,siemen-buve,NaN,Belgium,2005-01-15,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3515,NaN,NaN,NaN,NaN,Viktor Dolgyi,viktor-dolgyi,Ukraine,Ukraine,2004-01-02,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3516,NaN,NaN,NaN,NaN,Yusuf Yılmaz,yusuf-yilmaz,Türkiye,Türkiye,2006-04-29,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3517,Squad,NaN,NaN,NaN,Player,NaN,NaN,NaN,NaN,NaN,...,Stp%,#OPA,#OPA/90,AvgDist,Matches,Comp,Save%,PKsv,PKm,Save%

In [124]:
# Renaming columns for feature engineering
newest_dt.rename(columns = {'Touches Touches_x':'Overall Squad Touches'}, inplace = True)
newest_dt_GK.rename(columns = {'Touches Touches':'Overall Squad Touches'}, inplace = True)

# https://www.geeksforgeeks.org/how-to-rename-columns-in-pandas-dataframe/

In [125]:
# Creating a new feature that finds the average number of touches a club has for every 90 minutes of playing time
newest_dt['Average touches per 90 (club)'] = newest_dt['Overall Squad Touches'] / newest_dt['90s_x']
newest_dt_GK['Average touches per 90 (club)'] = newest_dt_GK['Overall Squad Touches'] / newest_dt['90s_x']

In [126]:
# Goalkeeper dataset does not have a player's average touches
# Thus it will be merged with the FBref possession dataset 
newest_dt_GK_1=newest_dt_GK.merge(df_FB_POSS, on='Player', how='outer')
newest_dt_GK_2=newest_dt_GK_1.drop(columns=['Touches Def Pen', 'Touches Def 3rd', 'Touches Mid 3rd',
                           'Touches Att 3rd', 'Touches Att Pen', 'Touches Live', 'Take-Ons Att',
                           'Take-Ons Succ', 'Take-Ons Succ%', 'Take-Ons Tkld', 'Take-Ons Tkld%',
                           'Carries Carries', 'Carries TotDist', 'Carries PrgDist', 'Carries PrgC',
                           'Carries 1/3', 'Carries CPA', 'Carries Mis', 'Carries Dis',
                           'Receiving Rec', 'Receiving PrgR'])
newest_dt_GK_2

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

# Adapted From:
# Title: Drafting the Perfect Prospect: Leveraging Data Science in MLB Draft Scenarios 
# Author: MaFisher
# Date: 2023
# Code Version: N/A
# https://mafisher.medium.com/drafting-the-perfect-prospect-leveraging-data-science-in-mlb-draft-scenarios-6444d9d7b89f

# Adapted From:
# Title: Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python
# Author: Sridhar Venkatachalam
# Date: No date
# Code Version: N/A
# Source: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/""

# Adapted From:
# Title: Python | Pandas dataframe.drop_duplicates()
# Author: Geeks for Geeks
# Date: 2024
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/"

,Squad,Poss,90s,Overall Squad Touches,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,Sweeper AvgDist,Matches,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Average touches per 90 (club),Rk,Touches Touches
0,Alavés,41.8,38.0,18179.0,Antonio Sivera,antonio-sivera,Spain,Spain,1996-08-11,Goalkeeper,...,13.1,Matches,es La Liga,75.6,0,0,0.0,478.394737,2449,1185
1,Alavés,41.8,38.0,18179.0,Jesús Owono,jesus-owono,Equatorial Guinea,Equatorial Guinea,2001-03-01,Goalkeeper,...,15.2,Matches,es La Liga,66.7,0,0,0,478.394737,2011,130
2,Almería,46.4,38.0,20902.0,Diego Mariño,diego-marino,Spain,Spain,1990-05-09,Goalkeeper,...,22.7,Matches,es La Liga,100.0,0,0,0.0,550.052632,1622,32
3,Almería,46.4,38.0,20902.0,Luís Maximiano,luis-maximiano,Portugal,Portugal,1999-01-05,Goalkeeper,...,14.5,Matches,es La Liga,66.3,1,2,20.0,550.052632,1679,1355
4,Almería,46.4,38.0,20902.0,Fernando,NaN,NaN,NaN,NaN,NaN,...,14.5,Matches,es La Liga,56.5,0,0,0,550.052632,870,169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6264,NaN,NaN,NaN,NaN,Lovro Zvonarek,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2848,73
6265,NaN,NaN,NaN,NaN,Martin Ødegaard,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2849,2326
6266,NaN,NaN,NaN,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850,421
6267,NaN,NaN,NaN,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2851,381
6268,NaN,NaN,NaN,NaN,Mateusz Łęgowski,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2852,504

,Squad,Poss,90s,Overall Squad Touches,Player,player_code,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,Sweeper AvgDist,Matches,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Average touches per 90 (club),Rk,Touches Touches
0,Alavés,41.8,38.0,18179.0,Antonio Sivera,antonio-sivera,Spain,Spain,1996-08-11,Goalkeeper,...,13.1,Matches,es La Liga,75.6,0,0,0.0,478.394737,2449,1185
1,Alavés,41.8,38.0,18179.0,Jesús Owono,jesus-owono,Equatorial Guinea,Equatorial Guinea,2001-03-01,Goalkeeper,...,15.2,Matches,es La Liga,66.7,0,0,0,478.394737,2011,130
2,Almería,46.4,38.0,20902.0,Diego Mariño,diego-marino,Spain,Spain,1990-05-09,Goalkeeper,...,22.7,Matches,es La Liga,100.0,0,0,0.0,550.052632,1622,32
3,Almería,46.4,38.0,20902.0,Luís Maximiano,luis-maximiano,Portugal,Portugal,1999-01-05,Goalkeeper,...,14.5,Matches,es La Liga,66.3,1,2,20.0,550.052632,1679,1355
4,Almería,46.4,38.0,20902.0,Fernando,NaN,NaN,NaN,NaN,NaN,...,14.5,Matches,es La Liga,56.5,0,0,0,550.052632,870,169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6264,NaN,NaN,NaN,NaN,Lovro Zvonarek,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2848,73
6265,NaN,NaN,NaN,NaN,Martin Ødegaard,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2849,2326
6266,NaN,NaN,NaN,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850,421
6267,NaN,NaN,NaN,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2851,381
6268,NaN,NaN,NaN,NaN,Mateusz Łęgowski,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2852,504

In [127]:
newest_dt_GK_3 = newest_dt_GK_2
newest_dt_1 = newest_dt

In [128]:
# Ensuring that the required data is numeric and columns have appropiate names
# errors='coerce' forces desired variable to become numeric
newest_dt_1['Touches'] = pd.to_numeric(newest_dt_1['Touches Touches_y'], errors='coerce')
newest_dt_GK_3['Touches'] = pd.to_numeric(newest_dt_GK_3['Touches Touches'], errors='coerce')

In [129]:
# Create a new feature called "Usage Rate %"
# This measures how much ball of the ball a player has in the game relative to the rest of their team
newest_dt['Usage Rate %'] = (newest_dt['Touches'] / newest_dt['Overall Squad Touches']) * 100
newest_dt_GK_3['Usage Rate %'] = (newest_dt_GK_3['Touches'] / newest_dt_GK['Overall Squad Touches']) * 100

# Adapted From:
# Title: Drafting the Perfect Prospect: Leveraging Data Science in MLB Draft Scenarios 
# Author: MaFisher
# Date: 2023
# Code Version: N/A
# https://mafisher.medium.com/drafting-the-perfect-prospect-leveraging-data-science-in-mlb-draft-scenarios-6444d9d7b89f

# Adapted From:
# Title: Average Passing Distance and Usage Rate in the English Premier League 
# Author: Raumdata
# Date: 2020
# Code Version: N/A
# Source: "https://raumdatafootball.com/2020/07/04/average-passing-distance-and-usage-rate-in-the-english-premier-league/"

In [130]:
# Dropping the final unnecessary columns for outfield players
newest_dt_1 = newest_dt.drop(columns=['90s_x', 'Rk_y', 'Rk', 'Rk_x', '90s_y',
                                     'player_code', 'Player_1',
                                     'Average touches per 90 (club)', 'Touches Touches_y', 'Overall Squad Touches',
                                     'Poss', 'Born_x', 'Pos_x', 'Matches_x', 'Matches_y', 'Squad_y',
                                     'Expected npxG+xAG', 'Nation_y', 'Comp_y', 'Pos_y', 'Age_y', 'Born_y'])
newest_dt_1

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Squad,Player,Performance Fls,Performance Fld,Performance Off,Performance Crs,Performance PKwon,Performance PKcon,Performance OG,Performance Recov,...,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur,Touches,Usage Rate %
0,Alavés,Abdel Abqar,33,23,1,2,0,2,1,109,...,Defender,right,188.0,2025-06-30 00:00:00,11MANGMT,Deportivo Alavés S.A.D.,3000000.0,3000000.0,1032.0,5.676880
1,Alavés,Carlos Benavídez,38,9,1,4,0,2,0,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,628.0,3.454535
2,Alavés,Antonio Blanco,36,40,0,15,0,0,0,160,...,Midfield,right,176.0,2027-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,5000000.0,5000000.0,1283.0,7.057594
3,Alavés,Rubén Duarte,31,30,0,70,0,0,0,93,...,Defender,left,179.0,2026-06-30 00:00:00,CAA Stellar,Deportivo Alavés S.A.D.,2500000.0,6000000.0,1024.0,5.632873
4,Alavés,Andoni Gorosabel,29,41,0,81,1,1,0,164,...,Defender,right,174.0,2024-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,2500000.0,10000000.0,1624.0,8.933385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30321,NaN,Sid Ahmed Aissaoui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0,NaN,NaN
30322,NaN,Erdem Çalık,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0,NaN,NaN
30323,NaN,Adama Sidibeh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN,NaN,NaN
30324,NaN,Artem Prysyazhnyuk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN,NaN,NaN
30325,NaN,Araphat Mohammed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN,NaN,NaN

,Squad,Player,Performance Fls,Performance Fld,Performance Off,Performance Crs,Performance PKwon,Performance PKcon,Performance OG,Performance Recov,...,position,foot,height_in_cm,contract_expiration_date,agent_name,current_club_name,market_value_in_eur,highest_market_value_in_eur,Touches,Usage Rate %
0,Alavés,Abdel Abqar,33,23,1,2,0,2,1,109,...,Defender,right,188.0,2025-06-30 00:00:00,11MANGMT,Deportivo Alavés S.A.D.,3000000.0,3000000.0,1032.0,5.676880
1,Alavés,Carlos Benavídez,38,9,1,4,0,2,0,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,628.0,3.454535
2,Alavés,Antonio Blanco,36,40,0,15,0,0,0,160,...,Midfield,right,176.0,2027-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,5000000.0,5000000.0,1283.0,7.057594
3,Alavés,Rubén Duarte,31,30,0,70,0,0,0,93,...,Defender,left,179.0,2026-06-30 00:00:00,CAA Stellar,Deportivo Alavés S.A.D.,2500000.0,6000000.0,1024.0,5.632873
4,Alavés,Andoni Gorosabel,29,41,0,81,1,1,0,164,...,Defender,right,174.0,2024-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,2500000.0,10000000.0,1624.0,8.933385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30321,NaN,Sid Ahmed Aissaoui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0,NaN,NaN
30322,NaN,Erdem Çalık,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0,NaN,NaN
30323,NaN,Adama Sidibeh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN,NaN,NaN
30324,NaN,Artem Prysyazhnyuk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN,NaN,NaN
30325,NaN,Araphat Mohammed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN,NaN,NaN

In [131]:
newest_dt_1.columns

Index(['Squad', 'Player', 'Performance Fls', 'Performance Fld',
       'Performance Off', 'Performance Crs', 'Performance PKwon',
       'Performance PKcon', 'Performance OG', 'Performance Recov',
       'Aerial Duels Won', 'Aerial Duels Lost', 'Aerial Duels Won%',
       'Nation_x', 'Comp_x', 'Age_x', 'Playing Time MP', 'Playing Time Starts',
       'Playing Time Min', 'Playing Time 90s', 'Performance Gls',
       'Performance Ast', 'Performance G+A', 'Performance G-PK',
       'Performance PK', 'Performance PKatt', 'Performance CrdY',
       'Performance CrdR', 'Expected xG', 'Expected npxG', 'Expected xAG',
       'Progression PrgC', 'Progression PrgP', 'Progression PrgR',
       'Per 90 Minutes Gls', 'Per 90 Minutes Ast', 'Per 90 Minutes G+A',
       'Per 90 Minutes G-PK', 'Per 90 Minutes G+A-PK', 'Per 90 Minutes xG',
       'Per 90 Minutes xAG', 'Per 90 Minutes xG+xAG', 'Per 90 Minutes npxG',
       'Per 90 Minutes npxG+xAG', 'Touches Def Pen', 'Touches Def 3rd',
       'Touches Mid 3rd', 'Touches Att 3rd', 'Touches Att Pen', 'Touches Live',
       'Take-Ons Att', 'Take-Ons Succ', 'Take-Ons Succ%', 'Take-Ons Tkld',
       'Take-Ons Tkld%', 'Carries Carries', 'Carries TotDist',
       'Carries PrgDist', 'Carries PrgC', 'Carries 1/3', 'Carries CPA',
       'Carries Mis', 'Carries Dis', 'Receiving Rec', 'Receiving PrgR',
       'Tackles Tkl', 'Tackles TklW', 'Tackles Def 3rd', 'Tackles Mid 3rd',
       'Tackles Att 3rd', 'Challenges Tkl', 'Challenges Att',
       'Challenges Tkl%', 'Challenges Lost', 'Blocks Blocks', 'Blocks Sh',
       'Blocks Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'country_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name',
       'current_club_name', 'market_value_in_eur',
       'highest_market_value_in_eur', 'Touches', 'Usage Rate %'],
      dtype='object')

Index(['Squad', 'Player', 'Performance Fls', 'Performance Fld',
       'Performance Off', 'Performance Crs', 'Performance PKwon',
       'Performance PKcon', 'Performance OG', 'Performance Recov',
       'Aerial Duels Won', 'Aerial Duels Lost', 'Aerial Duels Won%',
       'Nation_x', 'Comp_x', 'Age_x', 'Playing Time MP', 'Playing Time Starts',
       'Playing Time Min', 'Playing Time 90s', 'Performance Gls',
       'Performance Ast', 'Performance G+A', 'Performance G-PK',
       'Performance PK', 'Performance PKatt', 'Performance CrdY',
       'Performance CrdR', 'Expected xG', 'Expected npxG', 'Expected xAG',
       'Progression PrgC', 'Progression PrgP', 'Progression PrgR',
       'Per 90 Minutes Gls', 'Per 90 Minutes Ast', 'Per 90 Minutes G+A',
       'Per 90 Minutes G-PK', 'Per 90 Minutes G+A-PK', 'Per 90 Minutes xG',
       'Per 90 Minutes xAG', 'Per 90 Minutes xG+xAG', 'Per 90 Minutes npxG',
       'Per 90 Minutes npxG+xAG', 'Touches Def Pen', 'Touches Def 3rd',
       'Touches Mid 3rd', 'Touches Att 3rd', 'Touches Att Pen', 'Touches Live',
       'Take-Ons Att', 'Take-Ons Succ', 'Take-Ons Succ%', 'Take-Ons Tkld',
       'Take-Ons Tkld%', 'Carries Carries', 'Carries TotDist',
       'Carries PrgDist', 'Carries PrgC', 'Carries 1/3', 'Carries CPA',
       'Carries Mis', 'Carries Dis', 'Receiving Rec', 'Receiving PrgR',
       'Tackles Tkl', 'Tackles TklW', 'Tackles Def 3rd', 'Tackles Mid 3rd',
       'Tackles Att 3rd', 'Challenges Tkl', 'Challenges Att',
       'Challenges Tkl%', 'Challenges Lost', 'Blocks Blocks', 'Blocks Sh',
       'Blocks Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'country_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name',
       'current_club_name', 'market_value_in_eur',
       'highest_market_value_in_eur', 'Touches', 'Usage Rate %'],
      dtype='object')

In [132]:
# Dropping the final unnecessary columns for Goalkeepers
newest_dt_GK_4 = newest_dt_GK_3.drop(columns=['player_code', 'Poss', '90s', 'Overall Squad Touches',
                                             'Matches', 'Touches Touches', 'sub_position', 'Matches',
                                             'Average touches per 90 (club)', 'Pos'])
newest_dt_GK_4

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Squad,Player,country_of_birth,country_of_citizenship,date_of_birth,position,foot,height_in_cm,contract_expiration_date,agent_name,...,Sweeper #OPA/90,Sweeper AvgDist,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Rk,Touches,Usage Rate %
0,Alavés,Antonio Sivera,Spain,Spain,1996-08-11,Goalkeeper,right,185.0,2027-06-30 00:00:00,Wasserman,...,0.85,13.1,es La Liga,75.6,0,0,0.0,2449,1185.0,6.518510
1,Alavés,Jesús Owono,Equatorial Guinea,Equatorial Guinea,2001-03-01,Goalkeeper,both,181.0,2026-06-30 00:00:00,Wasserman,...,2.00,15.2,es La Liga,66.7,0,0,0,2011,130.0,0.715111
2,Almería,Diego Mariño,Spain,Spain,1990-05-09,Goalkeeper,right,185.0,2024-06-30 00:00:00,Promoesport,...,2.00,22.7,es La Liga,100.0,0,0,0.0,1622,32.0,0.153095
3,Almería,Luís Maximiano,Portugal,Portugal,1999-01-05,Goalkeeper,both,190.0,2024-06-30 00:00:00,MRP.POSITIONUMBER,...,1.15,14.5,es La Liga,66.3,1,2,20.0,1679,1355.0,6.482633
4,Almería,Fernando,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.75,14.5,es La Liga,56.5,0,0,0,870,169.0,0.808535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6264,NaN,Lovro Zvonarek,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2848,73.0,NaN
6265,NaN,Martin Ødegaard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2849,2326.0,NaN
6266,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850,421.0,NaN
6267,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2851,381.0,NaN
6268,NaN,Mateusz Łęgowski,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2852,504.0,NaN

,Squad,Player,country_of_birth,country_of_citizenship,date_of_birth,position,foot,height_in_cm,contract_expiration_date,agent_name,...,Sweeper #OPA/90,Sweeper AvgDist,Comp,Performance Save%,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%,Rk,Touches,Usage Rate %
0,Alavés,Antonio Sivera,Spain,Spain,1996-08-11,Goalkeeper,right,185.0,2027-06-30 00:00:00,Wasserman,...,0.85,13.1,es La Liga,75.6,0,0,0.0,2449,1185.0,6.518510
1,Alavés,Jesús Owono,Equatorial Guinea,Equatorial Guinea,2001-03-01,Goalkeeper,both,181.0,2026-06-30 00:00:00,Wasserman,...,2.00,15.2,es La Liga,66.7,0,0,0,2011,130.0,0.715111
2,Almería,Diego Mariño,Spain,Spain,1990-05-09,Goalkeeper,right,185.0,2024-06-30 00:00:00,Promoesport,...,2.00,22.7,es La Liga,100.0,0,0,0.0,1622,32.0,0.153095
3,Almería,Luís Maximiano,Portugal,Portugal,1999-01-05,Goalkeeper,both,190.0,2024-06-30 00:00:00,MRP.POSITIONUMBER,...,1.15,14.5,es La Liga,66.3,1,2,20.0,1679,1355.0,6.482633
4,Almería,Fernando,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.75,14.5,es La Liga,56.5,0,0,0,870,169.0,0.808535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6264,NaN,Lovro Zvonarek,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2848,73.0,NaN
6265,NaN,Martin Ødegaard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2849,2326.0,NaN
6266,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850,421.0,NaN
6267,NaN,Milan Đurić,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2851,381.0,NaN
6268,NaN,Mateusz Łęgowski,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2852,504.0,NaN

In [133]:
# Renaming all the columns to appropiate names
newest_dt_1 = newest_dt_1.rename(columns={'Performance Fls':'Fouls_Commited', 'Performance Fld':'Fouls_Won',
                                'Performance Off':'Offsides', 'Performance Crs':'Crosses', 
                                'Performance PKwon':'Penalties_Won', 'Performance PKcon':'Penalties_Conceded',
                                'Performance OG':'Own_Goals', 'Performance Recov':'Ball_Recoveries',
                                'Aerial Duels Won':'Aerial_Duels_Won', 'Aerial Duels Lost':'Aerial_Duels_Lost',
                                'Aerial Duels Won%':'Aerial_Duels_Won_Per',
                                'Age_x':'Age', 'Performance Gls': 'Goals', 'Rk_x':'Rank',
                                'Performance Ast':'Assists', 'Performance G+A':'Goals_and_Assists',
                                'Tackles Tkl': 'Tackles_Tkl', 'Expected npxG': 'Expected_npxG',
                                'Progression PrgC': 'Progression_PrgC', 'Progression PrgP': 'Progression_PrgP',
                                'Usage Rate %': 'Usage_Rate_Per', 'Tackles TklW':'Tackles_TklW', 'Blocks Blocks': 'Blocks',
                                'Challenges Att': 'Challenges_Att', 'Challenges Tkl%':'Challenges_Tkl_per',
                                'Challenges Lost':'Challenges_Lost', 'Performance CrdY':'Performance_CrdY',
                                'Performance CrdR': 'Performance_CrdR', 'Comp_x': 'Comp',
                                'Playing Time MP':'Playing_Time_MP', 'Playing Time Starts':'Playing_Time_Starts',
                                'Playing Time 90s':'Playing_Time_90s', 'Playing Time Min':'Playing_Time_Min',
                                'Expected xG':'Expected_xG', 'Performance G-PK':'Goals_Minus_PK',
                                'Performance PK':'Penalty_Goals', 'Performance PKatt':'Penalties_Attempted',
                                'Expected xAG':'Expected_xAG', 'Per 90 Minutes xG+xAG':'npxG_plus_xAG', 
                                'Progression PrgR':'Progression_PrgR', 
                                'Per 90 Minutes Gls':'Per_90_Min_Gls', 'Per_90_Minutes_Ast':'Per_90_Minutes_Ast', 
                                'Per 90 Minutes G+A':'Per_90_Min_Goal_Contributions', 
                                'Per 90 Minutes G-PK':'Per_90_Min_Non_Pen_Goals', 'Nation_x':'Nation',
                                'Per 90 Minutes G+A-PK':'Per_90_Min_Non_Penalty_Goal_Contributions', 
                                'Per 90 Minutes xG':'Per_90_Min_xG', 'Per 90 Minutes xAG':'Per_90_Min_xAG',
                                'Per 90 Minutes xG+xAG':'Per_90_Min_xG+xAG', 'Per 90 Minutes npxG':'Per_90_Min_npxG',
                                'Per 90 Minutes npxG+xAG':'Per_90_Min_npxG+xAG', 'Touches Def Pen':'Touches_Def_Pen', 
                                'Touches Def 3rd':'Touches_Def_3rd', 'Touches Mid 3rd':'Touches_Mid_3rd', 
                                'Touches Att 3rd':'Touches_Att_3rd', 'Touches Att Pen':'Touches_Att_Pen', 
                                'Touches Live':'Touches_Live', 'Take-Ons Att':'Take_Ons_Att', 
                                'Take-Ons Succ':'Take_Ons_Succ', 'Take-Ons Succ%':'Take_Ons_Succ_Per', 
                                'Take-Ons Tkld':'Take_Ons_Tkld','Take-Ons Tkld%':'Take_Ons_Tkld_Per', 
                                'Carries Carries':'Carries', 'Carries TotDist':'Carries_TotDist',
                                'Carries PrgDist':'Carries_PrgDist', 'Carries PrgC':'Carries_PrgC', 
                                'Carries 1/3':'Carries_Into_Final_1/3', 'Carries CPA':'Carries_Into_Penalty_Box',
                                'Carries Mis':'Miscontrol', 'Carries Dis':'Dispossessed', 'Receiving Rec':'Passes_Recieved', 
                                'Receiving PrgR':'Progressive_Passes_Recieved', 
                                'Tackles Def 3rd':'Tackles_Def_3rd', 'Tackles Mid 3rd':'Tackles_Mid_3rd', 
                                'Tackles Att 3rd':'Tackles_Att_3rd', 'Challenges Tkl':'Dribblers_Tkl', 
                                'Challenges Att':'Dribblers_Challenged','Challenges Tkl%':'Per_Dribblers_Tkl_Succ',
                                'Challenges Lost':'Challenges_Lost', 'Blocks Blocks':'Blocks', 'Blocks Sh':'Blocked_Shots',
                                'Blocks Pass':'Blocked_Passes', 'Int':'Interceptions', 'Tkl+Int':'Tkl_Plus_Int', 'Clr':'Clearances',
                                'Err':'Errors', 'Usage_Rate_%':'Usage_Rate_Per', 'country_of_birth':'Country_of_Birth',
                                'country_of_citizenship':'Country_of_Citizenship', 'sub_position':'Sub_Position', 
                                'position':'Position', 'foot':'Foot', 'height_in_cm':'Height_in_CM', 
                                'contract_expiration_date':'Contract_Expiration_Date', 'agent_name':'Agent_Name',
                                'current_club_name':'Current_Club_Name', 'market_value_in_eur':'Market_Value_in_Eur',
                                'highest_market_value_in_eur':'Highest_Market_Value_in_Eur'})
newest_dt_GK_4 = newest_dt_GK_4.rename(columns={'Performance Save%': 'Performance_Save_Per', 
                                                'Penalty Kicks PKsv':'Penalties_saved', 
                                                'Expected PSxG+/-':'PSxG_minus_GA', 'Crosses Stp%':'Crosses_Stp_Per',
                                                'Sweeper #OPA':'Number_of_Sweep', 'Expected /90':'PSxG_minus_GA_90',
                                                'Launched Cmp%':'Long_Pass_Acc_per', 'Passes Att (GK)':'Passes_Attempted',
                                                'Passes Thr':'Throws_Attemp', 'Passes Launch%':'Per_Passes_Launched', 
                                                'Passes AvgLen':'Avg_Pass_Length', 'Goal Kicks Att':'Goal_Kicks_Att',
                                                'Goal Kicks Launch%':'Per_Goal_Kicks_Launch', 
                                                'Goal Kicks AvgLen':'Avg_Length_Goal_Kick', 'Crosses Opp':'Crosses_Faced', 
                                                'Crosses Stp':'Crosses_Stp','Penalty Kicks Save%':'Penalty_Kick_Save_Per',
                                                'Usage Rate %':'Usage_Rate_Per', 'position':'Position', 'foot':'Foot',
                                                'Sweeper #OPA/90':'Number_of_Sweep_per_90', 
                                                'contract_expiration_date':'Contract_Expiration_Date', 
                                                'agent_name':'Agent_Name',
                                                'current_club_name':'Current_Club_Name', 
                                                'market_value_in_eur':'Market_Value_in_Eur',
                                                'highest_market_value_in_eur':'Highest_Market_Value_in_Eur',
                                                'country_of_birth':'Country_of_Birth', 
                                                'country_of_citizenship':'Country_of_Citizenship',
                                                'date_of_birth':'DOB', 'height_in_cm':'Height_in_CM',
                                                'Sweeper AvgDist':'Sweeper_Avg_Dist'})

In [134]:
# Extracting the 'Nation' variable's second word 
newest_dt_1['Nation'] = newest_dt_1['Nation'].str.split(' ').str.get(1)
newest_dt_1

# Adapted From:
# Title: How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights
# Author: Ricardo Andre
# Date: 2023
# Code Version: N/A
# Source: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"

,Squad,Player,Fouls_Commited,Fouls_Won,Offsides,Crosses,Penalties_Won,Penalties_Conceded,Own_Goals,Ball_Recoveries,...,Position,Foot,Height_in_CM,Contract_Expiration_Date,Agent_Name,Current_Club_Name,Market_Value_in_Eur,Highest_Market_Value_in_Eur,Touches,Usage_Rate_Per
0,Alavés,Abdel Abqar,33,23,1,2,0,2,1,109,...,Defender,right,188.0,2025-06-30 00:00:00,11MANGMT,Deportivo Alavés S.A.D.,3000000.0,3000000.0,1032.0,5.676880
1,Alavés,Carlos Benavídez,38,9,1,4,0,2,0,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,628.0,3.454535
2,Alavés,Antonio Blanco,36,40,0,15,0,0,0,160,...,Midfield,right,176.0,2027-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,5000000.0,5000000.0,1283.0,7.057594
3,Alavés,Rubén Duarte,31,30,0,70,0,0,0,93,...,Defender,left,179.0,2026-06-30 00:00:00,CAA Stellar,Deportivo Alavés S.A.D.,2500000.0,6000000.0,1024.0,5.632873
4,Alavés,Andoni Gorosabel,29,41,0,81,1,1,0,164,...,Defender,right,174.0,2024-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,2500000.0,10000000.0,1624.0,8.933385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30321,NaN,Sid Ahmed Aissaoui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0,NaN,NaN
30322,NaN,Erdem Çalık,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0,NaN,NaN
30323,NaN,Adama Sidibeh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN,NaN,NaN
30324,NaN,Artem Prysyazhnyuk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN,NaN,NaN
30325,NaN,Araphat Mohammed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN,NaN,NaN

,Squad,Player,Fouls_Commited,Fouls_Won,Offsides,Crosses,Penalties_Won,Penalties_Conceded,Own_Goals,Ball_Recoveries,...,Position,Foot,Height_in_CM,Contract_Expiration_Date,Agent_Name,Current_Club_Name,Market_Value_in_Eur,Highest_Market_Value_in_Eur,Touches,Usage_Rate_Per
0,Alavés,Abdel Abqar,33,23,1,2,0,2,1,109,...,Defender,right,188.0,2025-06-30 00:00:00,11MANGMT,Deportivo Alavés S.A.D.,3000000.0,3000000.0,1032.0,5.676880
1,Alavés,Carlos Benavídez,38,9,1,4,0,2,0,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,628.0,3.454535
2,Alavés,Antonio Blanco,36,40,0,15,0,0,0,160,...,Midfield,right,176.0,2027-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,5000000.0,5000000.0,1283.0,7.057594
3,Alavés,Rubén Duarte,31,30,0,70,0,0,0,93,...,Defender,left,179.0,2026-06-30 00:00:00,CAA Stellar,Deportivo Alavés S.A.D.,2500000.0,6000000.0,1024.0,5.632873
4,Alavés,Andoni Gorosabel,29,41,0,81,1,1,0,164,...,Defender,right,174.0,2024-06-30 00:00:00,NA,Deportivo Alavés S.A.D.,2500000.0,10000000.0,1624.0,8.933385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30321,NaN,Sid Ahmed Aissaoui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,183.0,2026-06-30 00:00:00,Aniss Benchabane,PFK CSKA Moskva,150000.0,150000.0,NaN,NaN
30322,NaN,Erdem Çalık,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,right,NA,2026-06-30 00:00:00,NA,Pendikspor,50000.0,50000.0,NaN,NaN
30323,NaN,Adama Sidibeh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Attack,NA,NA,2026-05-31 00:00:00,Willie McKay,Saint Johnstone Football Club,NaN,NaN,NaN,NaN
30324,NaN,Artem Prysyazhnyuk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,180.0,2025-05-31 00:00:00,NA,ZAO FK Chornomorets Odessa,NaN,NaN,NaN,NaN
30325,NaN,Araphat Mohammed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Midfield,left,NA,NA,NA,Fodbold Club Nordsjælland,NaN,NaN,NaN,NaN

In [135]:
# Using the "apply" method
# "errors = 'coerce'"
newest_dt_1[['Age', 'Playing_Time_MP',
       'Playing_Time_Starts', 'Playing_Time_Min', 'Playing_Time_90s', 'Goals',
       'Assists', 'Goals_and_Assists', 'Goals_Minus_PK', 'Penalty_Goals',
       'Penalties_Attempted', 'Performance_CrdY', 'Performance_CrdR',
       'Expected_xG', 'Expected_npxG', 'Expected_xAG',
       'Progression_PrgC', 'Progression_PrgP', 'Progression_PrgR',
       'Per_90_Min_Gls', 'Per 90 Minutes Ast', 'Per_90_Min_Goal_Contributions',
       'Per_90_Min_Non_Pen_Goals', 'Per_90_Min_Non_Penalty_Goal_Contributions',
       'Per_90_Min_xG', 'Per_90_Min_xAG', 'Per_90_Min_xG+xAG',
       'Per_90_Min_npxG', 'Per_90_Min_npxG+xAG', 'Touches_Def_Pen',
       'Touches_Def_3rd', 'Touches_Mid_3rd', 'Touches_Att_3rd',
       'Touches_Att_Pen', 'Touches_Live', 'Take_Ons_Att', 'Take_Ons_Succ',
       'Take_Ons_Succ_Per', 'Take_Ons_Tkld', 'Take_Ons_Tkld_Per', 'Carries',
       'Carries_TotDist', 'Carries_PrgDist', 'Carries_PrgC',
       'Carries_Into_Final_1/3', 'Carries_Into_Penalty_Box', 'Miscontrol',
       'Dispossessed', 'Passes_Recieved', 'Progressive_Passes_Recieved', 
       'Tackles_Tkl', 'Tackles_TklW', 'Tackles_Def_3rd',
       'Tackles_Mid_3rd', 'Tackles_Att_3rd', 'Dribblers_Tkl',
       'Dribblers_Challenged', 'Per_Dribblers_Tkl_Succ', 'Challenges_Lost',
       'Blocks', 'Blocked_Shots', 'Blocked_Passes', 'Interceptions',
       'Tkl_Plus_Int', 'Clearances', 'Errors',
       'Height_in_CM', 'Touches', 'Usage_Rate_Per',
       'Aerial_Duels_Won_Per', 'Aerial_Duels_Won',
       'Aerial_Duels_Lost', 'Fouls_Commited', 'Fouls_Won',
       'Offsides', 'Crosses', 
       'Penalties_Won', 'Penalties_Conceded',
       'Own_Goals', 'Ball_Recoveries']] = newest_dt_1[['Age', 'Playing_Time_MP','Playing_Time_Starts', 
                                                                    'Playing_Time_Min', 'Playing_Time_90s', 'Goals',
                                                                    'Assists', 'Goals_and_Assists', 'Goals_Minus_PK', 'Penalty_Goals',
                                                                    'Penalties_Attempted', 'Performance_CrdY', 'Performance_CrdR',
                                                                    'Expected_xG', 'Expected_npxG', 'Expected_xAG', 
                                                                    'Progression_PrgC', 'Progression_PrgP', 'Progression_PrgR',
                                                                    'Per_90_Min_Gls', 'Per 90 Minutes Ast', 'Per_90_Min_Goal_Contributions',
                                                                    'Per_90_Min_Non_Pen_Goals', 'Per_90_Min_Non_Penalty_Goal_Contributions',
                                                                    'Per_90_Min_xG', 'Per_90_Min_xAG', 'Per_90_Min_xG+xAG',
                                                                    'Per_90_Min_npxG', 'Per_90_Min_npxG+xAG', 'Touches_Def_Pen',
                                                                    'Touches_Def_3rd', 'Touches_Mid_3rd', 'Touches_Att_3rd',
                                                                    'Touches_Att_Pen', 'Touches_Live', 'Take_Ons_Att', 'Take_Ons_Succ',
                                                                    'Take_Ons_Succ_Per', 'Take_Ons_Tkld', 'Take_Ons_Tkld_Per', 'Carries',
                                                                    'Carries_TotDist', 'Carries_PrgDist', 'Carries_PrgC',
                                                                    'Carries_Into_Final_1/3', 'Carries_Into_Penalty_Box', 'Miscontrol',
                                                                    'Dispossessed', 'Passes_Recieved', 'Progressive_Passes_Recieved', 
                                                                    'Tackles_Tkl', 'Tackles_TklW', 'Tackles_Def_3rd',
                                                                    'Tackles_Mid_3rd', 'Tackles_Att_3rd', 'Dribblers_Tkl',
                                                                    'Dribblers_Challenged', 'Per_Dribblers_Tkl_Succ', 'Challenges_Lost',
                                                                    'Blocks', 'Blocked_Shots', 'Blocked_Passes', 'Interceptions',
                                                                    'Tkl_Plus_Int', 'Clearances', 'Errors',
                                                                    'Height_in_CM', 'Touches', 'Usage_Rate_Per',
                                                                    'Aerial_Duels_Won_Per', 'Aerial_Duels_Won',
                                                                    'Aerial_Duels_Lost', 'Fouls_Commited', 'Fouls_Won',
                                                                    'Offsides', 'Crosses', 
                                                                    'Penalties_Won', 'Penalties_Conceded',
                                                                    'Own_Goals', 'Ball_Recoveries']].apply(pd.to_numeric, errors='coerce')



# Adapted From:
# Title: pandas.to_numeric
# Author: Pandas
# Date: No date
# Code Version: 2.2
# Source: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html"

# Adapted From:
# Title: Change Data Type for one or more columns in Pandas Dataframe
# Author: Geeks for Geeks
# Date: 2023
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/change-data-type-for-one-or-more-columns-in-pandas-dataframe/"

In [136]:
newest_dt_GK_4[['Market_Value_in_Eur','Highest_Market_Value_in_Eur', 'PSxG_minus_GA','PSxG_minus_GA_90', 
                'Long_Pass_Acc_per', 'Passes_Attempted', 'Throws_Attemp', 'Per_Passes_Launched', 'Avg_Pass_Length',
                'Goal_Kicks_Att', 'Per_Goal_Kicks_Launch', 'Avg_Length_Goal_Kick', 'Crosses_Faced', 'Crosses_Stp', 
                'Crosses_Stp_Per', 'Number_of_Sweep','Number_of_Sweep_per_90', 'Sweeper_Avg_Dist', 'Performance_Save_Per', 
                'Penalties_saved', 'Penalty Kicks PKm','Penalty_Kick_Save_Per', 'Rk', 'Touches', 'Usage_Rate_Per']] = newest_dt_GK_4[['Market_Value_in_Eur','Highest_Market_Value_in_Eur', 'PSxG_minus_GA','PSxG_minus_GA_90', 
                                                                                                                                     'Long_Pass_Acc_per', 'Passes_Attempted', 'Throws_Attemp', 'Per_Passes_Launched', 'Avg_Pass_Length',
                                                                                                                                     'Goal_Kicks_Att', 'Per_Goal_Kicks_Launch', 'Avg_Length_Goal_Kick', 'Crosses_Faced', 'Crosses_Stp', 
                                                                                                                                     'Crosses_Stp_Per', 'Number_of_Sweep','Number_of_Sweep_per_90', 'Sweeper_Avg_Dist', 'Performance_Save_Per', 
                                                                                                                                     'Penalties_saved', 'Penalty Kicks PKm','Penalty_Kick_Save_Per', 'Rk', 'Touches', 'Usage_Rate_Per']].apply(pd.to_numeric, errors='coerce')



# Adapted From:
# Title: pandas.to_numeric
# Author: Pandas
# Date: No date
# Code Version: 2.2
# Source: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html"

# Adapted From:
# Title: Change Data Type for one or more columns in Pandas Dataframe
# Author: Geeks for Geeks
# Date: 2023
# Code Version: N/A
# Source: "https://www.geeksforgeeks.org/change-data-type-for-one-or-more-columns-in-pandas-dataframe/"

In [137]:
newest_dt_GK_4.columns

Index(['Squad', 'Player', 'Country_of_Birth', 'Country_of_Citizenship', 'DOB',
       'Position', 'Foot', 'Height_in_CM', 'Contract_Expiration_Date',
       'Agent_Name', 'Current_Club_Name', 'Market_Value_in_Eur',
       'Highest_Market_Value_in_Eur', 'Nation', 'Age', 'PSxG_minus_GA',
       'PSxG_minus_GA_90', 'Long_Pass_Acc_per', 'Passes_Attempted',
       'Throws_Attemp', 'Per_Passes_Launched', 'Avg_Pass_Length',
       'Goal_Kicks_Att', 'Per_Goal_Kicks_Launch', 'Avg_Length_Goal_Kick',
       'Crosses_Faced', 'Crosses_Stp', 'Crosses_Stp_Per', 'Number_of_Sweep',
       'Number_of_Sweep_per_90', 'Sweeper_Avg_Dist', 'Comp',
       'Performance_Save_Per', 'Penalties_saved', 'Penalty Kicks PKm',
       'Penalty_Kick_Save_Per', 'Rk', 'Touches', 'Usage_Rate_Per'],
      dtype='object')

Index(['Squad', 'Player', 'Country_of_Birth', 'Country_of_Citizenship', 'DOB',
       'Position', 'Foot', 'Height_in_CM', 'Contract_Expiration_Date',
       'Agent_Name', 'Current_Club_Name', 'Market_Value_in_Eur',
       'Highest_Market_Value_in_Eur', 'Nation', 'Age', 'PSxG_minus_GA',
       'PSxG_minus_GA_90', 'Long_Pass_Acc_per', 'Passes_Attempted',
       'Throws_Attemp', 'Per_Passes_Launched', 'Avg_Pass_Length',
       'Goal_Kicks_Att', 'Per_Goal_Kicks_Launch', 'Avg_Length_Goal_Kick',
       'Crosses_Faced', 'Crosses_Stp', 'Crosses_Stp_Per', 'Number_of_Sweep',
       'Number_of_Sweep_per_90', 'Sweeper_Avg_Dist', 'Comp',
       'Performance_Save_Per', 'Penalties_saved', 'Penalty Kicks PKm',
       'Penalty_Kick_Save_Per', 'Rk', 'Touches', 'Usage_Rate_Per'],
      dtype='object')

In [138]:
newest_dt_1.columns

Index(['Squad', 'Player', 'Fouls_Commited', 'Fouls_Won', 'Offsides', 'Crosses',
       'Penalties_Won', 'Penalties_Conceded', 'Own_Goals', 'Ball_Recoveries',
       'Aerial_Duels_Won', 'Aerial_Duels_Lost', 'Aerial_Duels_Won_Per',
       'Nation', 'Comp', 'Age', 'Playing_Time_MP', 'Playing_Time_Starts',
       'Playing_Time_Min', 'Playing_Time_90s', 'Goals', 'Assists',
       'Goals_and_Assists', 'Goals_Minus_PK', 'Penalty_Goals',
       'Penalties_Attempted', 'Performance_CrdY', 'Performance_CrdR',
       'Expected_xG', 'Expected_npxG', 'Expected_xAG', 'Progression_PrgC',
       'Progression_PrgP', 'Progression_PrgR', 'Per_90_Min_Gls',
       'Per 90 Minutes Ast', 'Per_90_Min_Goal_Contributions',
       'Per_90_Min_Non_Pen_Goals', 'Per_90_Min_Non_Penalty_Goal_Contributions',
       'Per_90_Min_xG', 'Per_90_Min_xAG', 'Per_90_Min_xG+xAG',
       'Per_90_Min_npxG', 'Per_90_Min_npxG+xAG', 'Touches_Def_Pen',
       'Touches_Def_3rd', 'Touches_Mid_3rd', 'Touches_Att_3rd',
       'Touches_Att_Pen', 'Touches_Live', 'Take_Ons_Att', 'Take_Ons_Succ',
       'Take_Ons_Succ_Per', 'Take_Ons_Tkld', 'Take_Ons_Tkld_Per', 'Carries',
       'Carries_TotDist', 'Carries_PrgDist', 'Carries_PrgC',
       'Carries_Into_Final_1/3', 'Carries_Into_Penalty_Box', 'Miscontrol',
       'Dispossessed', 'Passes_Recieved', 'Progressive_Passes_Recieved',
       'Tackles_Tkl', 'Tackles_TklW', 'Tackles_Def_3rd', 'Tackles_Mid_3rd',
       'Tackles_Att_3rd', 'Dribblers_Tkl', 'Dribblers_Challenged',
       'Per_Dribblers_Tkl_Succ', 'Challenges_Lost', 'Blocks', 'Blocked_Shots',
       'Blocked_Passes', 'Interceptions', 'Tkl_Plus_Int', 'Clearances',
       'Errors', 'Country_of_Birth', 'Country_of_Citizenship', 'date_of_birth',
       'Sub_Position', 'Position', 'Foot', 'Height_in_CM',
       'Contract_Expiration_Date', 'Agent_Name', 'Current_Club_Name',
       'Market_Value_in_Eur', 'Highest_Market_Value_in_Eur', 'Touches',
       'Usage_Rate_Per'],
      dtype='object')

Index(['Squad', 'Player', 'Fouls_Commited', 'Fouls_Won', 'Offsides', 'Crosses',
       'Penalties_Won', 'Penalties_Conceded', 'Own_Goals', 'Ball_Recoveries',
       'Aerial_Duels_Won', 'Aerial_Duels_Lost', 'Aerial_Duels_Won_Per',
       'Nation', 'Comp', 'Age', 'Playing_Time_MP', 'Playing_Time_Starts',
       'Playing_Time_Min', 'Playing_Time_90s', 'Goals', 'Assists',
       'Goals_and_Assists', 'Goals_Minus_PK', 'Penalty_Goals',
       'Penalties_Attempted', 'Performance_CrdY', 'Performance_CrdR',
       'Expected_xG', 'Expected_npxG', 'Expected_xAG', 'Progression_PrgC',
       'Progression_PrgP', 'Progression_PrgR', 'Per_90_Min_Gls',
       'Per 90 Minutes Ast', 'Per_90_Min_Goal_Contributions',
       'Per_90_Min_Non_Pen_Goals', 'Per_90_Min_Non_Penalty_Goal_Contributions',
       'Per_90_Min_xG', 'Per_90_Min_xAG', 'Per_90_Min_xG+xAG',
       'Per_90_Min_npxG', 'Per_90_Min_npxG+xAG', 'Touches_Def_Pen',
       'Touches_Def_3rd', 'Touches_Mid_3rd', 'Touches_Att_3rd',
       'Touches_Att_Pen', 'Touches_Live', 'Take_Ons_Att', 'Take_Ons_Succ',
       'Take_Ons_Succ_Per', 'Take_Ons_Tkld', 'Take_Ons_Tkld_Per', 'Carries',
       'Carries_TotDist', 'Carries_PrgDist', 'Carries_PrgC',
       'Carries_Into_Final_1/3', 'Carries_Into_Penalty_Box', 'Miscontrol',
       'Dispossessed', 'Passes_Recieved', 'Progressive_Passes_Recieved',
       'Tackles_Tkl', 'Tackles_TklW', 'Tackles_Def_3rd', 'Tackles_Mid_3rd',
       'Tackles_Att_3rd', 'Dribblers_Tkl', 'Dribblers_Challenged',
       'Per_Dribblers_Tkl_Succ', 'Challenges_Lost', 'Blocks', 'Blocked_Shots',
       'Blocked_Passes', 'Interceptions', 'Tkl_Plus_Int', 'Clearances',
       'Errors', 'Country_of_Birth', 'Country_of_Citizenship', 'date_of_birth',
       'Sub_Position', 'Position', 'Foot', 'Height_in_CM',
       'Contract_Expiration_Date', 'Agent_Name', 'Current_Club_Name',
       'Market_Value_in_Eur', 'Highest_Market_Value_in_Eur', 'Touches',
       'Usage_Rate_Per'],
      dtype='object')

In [139]:
# Save the DataFrame to a CSV file with utf-8 encoding
newest_dt_1.to_csv('file4.csv', encoding='utf-8-sig', index=False)

In [140]:
# Save the DataFrame to a CSV file with utf-8 encoding
newest_dt_GK_4.to_csv('file4_GK.csv', encoding='utf-8-sig', index=False)

In [141]:
'''Reference List

Andre, R. (2023)  How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights. 
Medium [online].
Available at: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"
[Accessed on: 5th June 2024]

Cariboo, D. (2024)  ‘Football Data from Transfermarkt’. Kaggle [online]. 
Available at: https://www.kaggle.com/datasets/davidcariboo/player-scores/data [Accessed on: 20th May 2024]

FBref (No date) 2023-2024 Big 5 European Leagues: Advanced Goalkeeping. FBref [online]. 
Available at: https://fbref.com/en/comps/Big5/2023-2024/keepersadv/players/2023-2024-Big-5-European-Leagues-Stats
[Accessed on: 3rd June 2024]

FBref (No date) 2023-2024 Big 5 European Leagues: Goalkeeping. FBref [online]. 
Available at: https://fbref.com/en/comps/Big5/2023-2024/keepers/players/2023-2024-Big-5-European-Leagues-Stats
[Accessed on: 3rd June 2024]

FBref (No date) 2023-2024 Big 5 European Leagues: Defensive Actions. FBref [online]. 
Available at: https://fbref.com/en/comps/Big5/2023-2024/defense/players/2023-2024-Big-5-European-Leagues-Stats
[Accessed on: 3rd June 2024]

FBref (No date) 2023-2024 Big 5 European Leagues: Miscellaneous Stats. FBref [online]. 
Available at: https://fbref.com/en/comps/Big5/2023-2024/misc/players/2023-2024-Big-5-European-Leagues-Stats
[Accessed on: 3rd June 2024]

FBref (No date) 2023-2024 Big 5 European Leagues: Possession. FBref [online]. 
Available at: https://fbref.com/en/comps/Big5/2023-2024/possession/players/2023-2024-Big-5-European-Leagues-Stats
[Accessed on: 3rd June 2024]

FBref (No date) 2023-2024 Big 5 European Leagues: Possession (Squad). FBref [online]. 
Available at: https://fbref.com/en/comps/Big5/2023-2024/possession/squads/2023-2024-Big-5-European-Leagues-Stats
[Accessed on: 3rd June 2024]

FBref (No date) 2023-2024 Big 5 European Leagues: Standard Stats. FBref [online]. 
Available at: https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats
[Accessed on: 3rd June 2024]

Geeks for Geeks (2020) Python | Pandas dataframe.drop_duplicates(). Geeks for Geeks [online].
Available at: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/" [Accessed on: 6th June 2024]

OpenAI (2024) ChatGPT [online]. Available from: https://chat.openai.com/ [Accessed June 3rd 2024]

Pandas (No date) Title: User Guide - Pandas. Pandas. Available at: "https://pandas.pydata.org/docs/user_guide/index.html"
[Accessed on: 5th August 2024]

Venkatachalam, S. (2020) Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python. 
Data science made simple [online] Available at: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/"
[Accessed on: 4th June 2024]

Pandas (No date) pandas.DataFrame.drop. Pandas [online]. Code Version: 2.2.
Available at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html"
[Accessed on: 4th June 2024]

Pandas (no date) pandas.to_numeric. Pandas. Code Version: 2.2.
Available at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html"
[Accessed on: 9th June 2024]

Geeks for Geeks (2023) Change Data Type for one or more columns in Pandas Dataframe. Geeks for Geeks [online]
Available at: Source: "https://www.geeksforgeeks.org/change-data-type-for-one-or-more-columns-in-pandas-dataframe/"
[Accessed on: 9th June 2024]

Pandas (No date) pandas.DataFrame.replace. Pandas [online]. Code Version: 2.2.
Available at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html"
[Accessed on: 6th June 2024]

Raumdata (2020) Average Passing Distance and Usage Rate in the English Premier League. Raumdata. Available at:
https://raumdatafootball.com/2020/07/04/average-passing-distance-and-usage-rate-in-the-english-premier-league/ [Accessed on: 15th July 2024]

Shaw and Holland (2019) Hierarchical Big data landscape Model. Research In Progress. 
In: Lecture notes and personal correspondence. Algorithms I. CP Holland, Loughborough University, (2024).

W3 Schools (No date) Pandas DataFrame isin() Method. W3 Schools.
Available at: "https://www.w3schools.com/python/pandas/ref_df_isin.asp"
[Accessed on: 6th June 2024]
'''

'Reference List\n\nAndre, R. (2023)  How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights. \nMedium [online].\nAvailable at: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"\n[Accessed on: 5th June 2024]\n\nCariboo, D. (2024)  ‘Football Data from Transfermarkt’. Kaggle [online]. \nAvailable at: https://www.kaggle.com/datasets/davidcariboo/player-scores/data [Accessed on: 20th May 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Advanced Goalkeeping. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/keepersadv/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Goalkeeping. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/keepers/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Defensive Actions. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/defense/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Miscellaneous Stats. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/misc/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Possession. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/possession/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Possession (Squad). FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/possession/squads/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Standard Stats. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nGeeks for Geeks (2020) Python | Pandas dataframe.drop_duplicates(). Geeks for Geeks [online].\nAvailable at: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/" [Accessed on: 6th June 2024]\n\nOpenAI (2024) ChatGPT [online]. Available from: https://chat.openai.com/ [Accessed June 3rd 2024]\n\nPandas (No date) Title: User Guide - Pandas. Pandas. Available at: "https://pandas.pydata.org/docs/user_guide/index.html"\n[Accessed on: 5th August 2024]\n\nVenkatachalam, S. (2020) Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python. \nData science made simple [online] Available at: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/"\n[Accessed on: 4th June 2024]\n\nPandas (No date) pandas.DataFrame.drop. Pandas [online]. Code Version: 2.2.\nAvailable at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html"\n[Accessed on: 4th June 2024]\n\nPandas (no date) pandas.to_numeric. Pandas. Code Version: 2.2.\nAvailable at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html"\n[Accessed on: 9th June 2024]\n\nGeeks for Geeks (2023) Change Data Type for one or more columns in Pandas Dataframe. Geeks for Geeks [online]\nAvailable at: Source: "https://www.geeksforgeeks.org/change-data-type-for-one-or-more-columns-in-pandas-dataframe/"\n[Accessed on: 9th June 2024]\n\nPandas (No date) pandas.DataFrame.replace. Pandas [online]. Code Version: 2.2.\nAvailable at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html"\n[Accessed on: 6th June 2024]\n\nRaumdata (2020) Average Passing Distance and Usage Rate in the English Premier League. Raumdata. Available at:\nhttps://raumdatafootball.com/2020/07/04/average-passing-distance-and-usage-rate-in-the-english-premier-league/ [Accessed on: 15th July 2024]\n\nShaw and Holland (2019) Hierarchical Big data landscape Model. Research In Progress. \nIn: Lecture notes and personal correspondence. Algorithms I. CP Holland, Loughborough University, (2024).\n\nW3 Schools (No date) Pandas DataFrame isin() Method. W3 Schools.\nAvailable at: "https://www.w3schools.com/python/pandas/ref_df_isin.asp"\n[Accessed on: 6th June 2024]\n'

'Reference List\n\nAndre, R. (2023)  How to scrape and personalize data from FBref with Python: A guide to unlocking Football Insights. \nMedium [online].\nAvailable at: "https://medium.com/@ricardoandreom/how-to-scrape-and-personalize-data-from-fbref-with-python-a-guide-to-unlocking-football-insights-7e623607afca"\n[Accessed on: 5th June 2024]\n\nCariboo, D. (2024)  ‘Football Data from Transfermarkt’. Kaggle [online]. \nAvailable at: https://www.kaggle.com/datasets/davidcariboo/player-scores/data [Accessed on: 20th May 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Advanced Goalkeeping. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/keepersadv/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Goalkeeping. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/keepers/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Defensive Actions. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/defense/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Miscellaneous Stats. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/misc/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Possession. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/possession/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Possession (Squad). FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/possession/squads/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nFBref (No date) 2023-2024 Big 5 European Leagues: Standard Stats. FBref [online]. \nAvailable at: https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats\n[Accessed on: 3rd June 2024]\n\nGeeks for Geeks (2020) Python | Pandas dataframe.drop_duplicates(). Geeks for Geeks [online].\nAvailable at: "https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/" [Accessed on: 6th June 2024]\n\nOpenAI (2024) ChatGPT [online]. Available from: https://chat.openai.com/ [Accessed June 3rd 2024]\n\nPandas (No date) Title: User Guide - Pandas. Pandas. Available at: "https://pandas.pydata.org/docs/user_guide/index.html"\n[Accessed on: 5th August 2024]\n\nVenkatachalam, S. (2020) Join in Pandas: Merge data frames (inner, outer, right, left join) in pandas python. \nData science made simple [online] Available at: "https://www.datasciencemadesimple.com/join-merge-data-frames-pandas-python/"\n[Accessed on: 4th June 2024]\n\nPandas (No date) pandas.DataFrame.drop. Pandas [online]. Code Version: 2.2.\nAvailable at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html"\n[Accessed on: 4th June 2024]\n\nPandas (no date) pandas.to_numeric. Pandas. Code Version: 2.2.\nAvailable at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html"\n[Accessed on: 9th June 2024]\n\nGeeks for Geeks (2023) Change Data Type for one or more columns in Pandas Dataframe. Geeks for Geeks [online]\nAvailable at: Source: "https://www.geeksforgeeks.org/change-data-type-for-one-or-more-columns-in-pandas-dataframe/"\n[Accessed on: 9th June 2024]\n\nPandas (No date) pandas.DataFrame.replace. Pandas [online]. Code Version: 2.2.\nAvailable at: "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html"\n[Accessed on: 6th June 2024]\n\nRaumdata (2020) Average Passing Distance and Usage Rate in the English Premier League. Raumdata. Available at:\nhttps://raumdatafootball.com/2020/07/04/average-passing-distance-and-usage-rate-in-the-english-premier-league/ [Accessed on: 15th July 2024]\n\nShaw and Holland (2019) Hierarchical Big data landscape Model. Research In Progress. \nIn: Lecture notes and personal correspondence. Algorithms I. CP Holland, Loughborough University, (2024).\n\nW3 Schools (No date) Pandas DataFrame isin() Method. W3 Schools.\nAvailable at: "https://www.w3schools.com/python/pandas/ref_df_isin.asp"\n[Accessed on: 6th June 2024]\n'

In [142]:
'''Furthermore, I acknowledge the use of OpenAI (source: https://chat.openai.com/) to aid me in making sure my code 
was efficient and working, using it to help me with errors, structure and understanding the code, which was included in the
work submitted for assessment. I confirm that all use of AI content is acknowledged and referenced appropriately.
1)The following prompt was input into (OpenAI: 
[“# creating a list with new names
new_columns = []
for col in df.columns:
 if 'level_0' in col:
     new_col = col.split()[-1]  # takes the last name
 else:
     new_col = col
 new_columns.append(new_col)

# rename columns
df.columns = new_columns
df = df.fillna(0)

df.head()” This code is not generating an output with the desired dataset, what is the error? And how could I fix it?] 

The output obtained was: 
(“The issue seems to be in your loop where you're creating the list new_col for renaming columns. It appears that the loop is intended to rename columns by removing 'level_0' from column names if present. However, it seems there's a typo in the variable assignment inside the loop (new_col_name vs new_column_name).
Here's the corrected code:
python
Copy code
# creating a list with new names
new_columns = []
for col in df.columns:
    if 'level_0' in col:
        new_col = col.split()[-1]
        new_coloumns.append(new_col_name)  # Fixed variable name here
    else:
        new_coloumns.append(col)  # Append unchanged column name if 'level_0' is not present

# rename columns
df.columns = new_col
df = df.fillna(0)

df.head()

With this correction, the code should work as intended, renaming columns by removing 'level_0' if present and filling any NaN 
values with 0.”)

Using this corrected output I adapted it to my code including by renaming the variable, using my own web scrapped datasets as 
the input, etc. 

'''

"Furthermore, I acknowledge the use of OpenAI (source: https://chat.openai.com/)\u202fto aid me in making sure my code \nwas efficient and working, using it to help me with errors, structure and understanding the code, which was included in the\nwork submitted for assessment. I confirm that all use of AI content is acknowledged and referenced appropriately.\n1)The following prompt was input into (OpenAI: \n[“# creating a list with new names\nnew_columns = []\nfor col in df.columns:\n if 'level_0' in col:\n     new_col = col.split()[-1]  # takes the last name\n else:\n     new_col = col\n new_columns.append(new_col)\n\n# rename columns\ndf.columns = new_columns\ndf = df.fillna(0)\n\ndf.head()” This code is not generating an output with the desired dataset, what is the error? And how could I fix it?] \n\nThe output obtained was: \n(“The issue seems to be in your loop where you're creating the list new_col for renaming columns. It appears that the loop is intended to rename columns by removing 'level_0' from column names if present. However, it seems there's a typo in the variable assignment inside the loop (new_col_name vs new_column_name).\nHere's the corrected code:\npython\nCopy code\n# creating a list with new names\nnew_columns = []\nfor col in df.columns:\n    if 'level_0' in col:\n        new_col = col.split()[-1]\n        new_coloumns.append(new_col_name)  # Fixed variable name here\n    else:\n        new_coloumns.append(col)  # Append unchanged column name if 'level_0' is not present\n\n# rename columns\ndf.columns = new_col\ndf = df.fillna(0)\n\ndf.head()\n\nWith this correction, the code should work as intended, renaming columns by removing 'level_0' if present and filling any NaN \nvalues with 0.”)\n\nUsing this corrected output I adapted it to my code including by renaming the variable, using my own web scrapped datasets as \nthe input, etc. \n\n"

"Furthermore, I acknowledge the use of OpenAI (source: https://chat.openai.com/)\u202fto aid me in making sure my code \nwas efficient and working, using it to help me with errors, structure and understanding the code, which was included in the\nwork submitted for assessment. I confirm that all use of AI content is acknowledged and referenced appropriately.\n1)The following prompt was input into (OpenAI: \n[“# creating a list with new names\nnew_columns = []\nfor col in df.columns:\n if 'level_0' in col:\n     new_col = col.split()[-1]  # takes the last name\n else:\n     new_col = col\n new_columns.append(new_col)\n\n# rename columns\ndf.columns = new_columns\ndf = df.fillna(0)\n\ndf.head()” This code is not generating an output with the desired dataset, what is the error? And how could I fix it?] \n\nThe output obtained was: \n(“The issue seems to be in your loop where you're creating the list new_col for renaming columns. It appears that the loop is intended to rename columns by removing 'level_0' from column names if present. However, it seems there's a typo in the variable assignment inside the loop (new_col_name vs new_column_name).\nHere's the corrected code:\npython\nCopy code\n# creating a list with new names\nnew_columns = []\nfor col in df.columns:\n    if 'level_0' in col:\n        new_col = col.split()[-1]\n        new_coloumns.append(new_col_name)  # Fixed variable name here\n    else:\n        new_coloumns.append(col)  # Append unchanged column name if 'level_0' is not present\n\n# rename columns\ndf.columns = new_col\ndf = df.fillna(0)\n\ndf.head()\n\nWith this correction, the code should work as intended, renaming columns by removing 'level_0' if present and filling any NaN \nvalues with 0.”)\n\nUsing this corrected output I adapted it to my code including by renaming the variable, using my own web scrapped datasets as \nthe input, etc. \n\n"